// Copyright 2022-2023 XMOS LIMITED.
// This Software is subject to the terms of the XCORE VocalFusion Licence.


// This file contains the framework for SHF including plumbing in and out of i2s/audio,
// the cross tile link for forwarding samples to and from PP and the fork and join
// constructs for parallelising the execution of the algorithm.

#include "xcore/chanend.h"
#define DEBUG_UNIT SHF_WRAPPER
#ifndef DEBUG_PRINT_ENABLE_SHF_WRAPPER
    #define DEBUG_PRINT_ENABLE_SHF_WRAPPER 0
#endif

#ifndef FIXED_BEAMS_ENABLED
#define FIXED_BEAMS_ENABLED 0
#endif

#include "debug_print.h"

#include "shf_wrapper.h"

#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <xcore/hwtimer.h>
#include <xcore/interrupt_wrappers.h>
#include <xcore/interrupt.h>
#include <xcore/triggerable.h>
#include "xcore/channel.h"
#include <string.h>

#include "app_conf.h"
#include "shf.h"
#include "shf_init.h"
#include "shf_bypass/shf_bypass.h"
#include "tile_common.h"
#include "shf_defaults.h"
#include "packet_queue.h"
#include "aec_cmds.h" // Autogenerated
#include "pp_cmds.h" // Autogenerated
#include "doa_smoothing.h"
#include "fixed_beam_gating.h"
DECLARE_INTERRUPT_CALLBACK(ep0_setup_pkt_recv_isr, app_data);

/* *************************
 * Macros
 * *************************/

#define DEBUG_PRINT_WORKER_BURN_THREADS     0   //Print progress of the SHF worker threads or not

#define DUMMY_WAIT_PERCENTAGE       98.9f   // The amount of time the busy wait test task keeps running as a proportiuon of frame frequency
#define AEC_DUMMY_WAIT_TICKS        (uint32_t)((float)SHF_FRAME_TIME_TICKS * DUMMY_WAIT_PERCENTAGE / 100.0)
#define PP_DUMMY_WAIT_TICKS         (uint32_t)((float)SHF_FRAME_TIME_TICKS * DUMMY_WAIT_PERCENTAGE / 100.0)

#define SETSR(c)                asm volatile("setsr %0" : : "n"(c));
#define SET_HIGH_PRIORITY()     SETSR(XS1_SR_QUEUE_MASK)    // Force the xcore to schedule once every 5 processor clocks
#define SET_FAST_MODE()         SETSR(XS1_SR_FAST_MASK)     // Force the xcore to schedule even if blocked on event
#define TIME_AFTER(A, B) ((int)((B) - (A)) < 0)

/* *************************
 * Function declarations
 * *************************/


/* *************************
 * Static data
 * *************************/

static unsigned shf_out_buf_num = 0;
static shf_output_t shf_output_buf[NUM_SHF_OUTPUT_BUFFERS] = {{{{0}}}};

/* *************************
 * function definitions
 * *************************/

void process_aec_control_command(control_pkt_t *pkt, aec_state_t* aec_state)
{
    static uint32_t far_mic_index[2] = {0};
    debug_printf("AEC Received %d command!!\n",pkt->cmd_id);
    uint8_t cmd = CONTROL_CMD_CLEAR_READ(pkt->cmd_id);
    if(SHF_Is_SHF_command_index(cmd))
    {
        if (IS_CONTROL_CMD_READ(pkt->cmd_id)) {
            SHF_GetPar_AEC(cmd, &pkt->payload[0]);
        }
        else {
            SHF_SetPar_AEC(cmd, &pkt->payload[0]);
        }
    }
    else
    {
        if (IS_CONTROL_CMD_READ(pkt->cmd_id))
        {
            switch(cmd) {
            case AEC_RESID_SPECIAL_CMD_AEC_FILTER_LENGTH:
            {
                uint32_t filter_len = SHF_AEC_LENGTH * SHF_NUM_BANDS;
                memcpy(pkt->payload, &filter_len, sizeof(uint32_t));
            }
            break;
            case AEC_RESID_SPECIAL_CMD_AEC_FILTER_COEFFS:
            {
                SHF_GetAECCoefs_AEC(far_mic_index[0], far_mic_index[1], pkt->payload_len, (float*)pkt->payload);
            }
            break;
            case AEC_RESID_AEC_NUM_MICS:
            {
                *((int32_t*)pkt->payload) = BECLEAR_NUMBER_OF_MICS;
            }
            break;
            case AEC_RESID_AEC_NUM_FARENDS:
            {
                *((int32_t*)pkt->payload) = BECLEAR_MAX_NUMBER_OF_FARENDS;
            }
            break;
            case AEC_RESID_AEC_MIC_ARRAY_TYPE:
            {
                *((int32_t*)pkt->payload) = MIC_ARRAY_TYPE;
            }
            break;
            case AEC_RESID_AEC_MIC_ARRAY_GEO:
            {
                for (int mic_i =0 ; mic_i < BECLEAR_NUMBER_OF_MICS; mic_i++) {
                    memcpy(pkt->payload + mic_i * sizeof(float)*3, aec_state->micpos[mic_i], sizeof(float)*3);
                }
            }
            break;
            case AEC_RESID_AEC_AZIMUTH_VALUES:
            {
                float spenergy[BECLEAR_NUMBER_OF_OUTPUTS];
                SHF_Get_azimuths(pkt->payload, spenergy, AEC_RESID_AEC_AZIMUTH_VALUES_NUM_VALUES);
            }
            break;
            case AEC_RESID_AEC_SPENERGY_VALUES:
            {
                float azimuths[BECLEAR_NUMBER_OF_OUTPUTS];
                SHF_Get_azimuths(azimuths, pkt->payload, AEC_RESID_AEC_SPENERGY_VALUES_NUM_VALUES);
            }
            break;
// RESID_X_NUM_VALUES is a macro, but RESID_X is an enum member so can't #ifdef
#ifdef AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES:
            {
                float elevation[BECLEAR_NUMBER_OF_BEAMS];
                SHF_Get_fixed_beams_azimuths(pkt->payload, elevation, AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES_NUM_VALUES);
            }
            break;
#endif
#ifdef AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES:
            {
                float azimuths[BECLEAR_NUMBER_OF_BEAMS];
                SHF_Get_fixed_beams_azimuths(azimuths, pkt->payload, AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES_NUM_VALUES);
            }
            break;
#endif
#ifdef AEC_RESID_AEC_FIXEDBEAMSGATING_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSGATING:
            {
                memcpy(pkt->payload, &aec_state->fixed_beams_gated, sizeof(aec_state->fixed_beams_gated));
            }
            break;
#endif
            case AEC_RESID_SHF_BYPASS:
            {
                memcpy(pkt->payload, &aec_state->bypass, sizeof(aec_state->bypass));
            }
            break;
            case AEC_RESID_AEC_CURRENT_IDLE_TIME:
            {
                memcpy(pkt->payload, &aec_state->idle_time_ticks, sizeof(aec_state->idle_time_ticks));
            }
            break;
            case AEC_RESID_AEC_MIN_IDLE_TIME:
            {
                memcpy(pkt->payload, &aec_state->min_idle_time_ticks, sizeof(aec_state->min_idle_time_ticks));
            }
            break;
            default:
            {
                xassert(0);
            }
            break;
            }
        }
        else
        {
            switch(cmd) {
            case AEC_RESID_SPECIAL_CMD_AEC_FAR_MIC_INDEX:
            {
                memcpy(far_mic_index, pkt->payload, pkt->payload_len);
            }
            break;
            case AEC_RESID_SPECIAL_CMD_AEC_FILTER_COEFFS:
            {
                SHF_SetAECCoefs_AEC(far_mic_index[0], far_mic_index[1], pkt->payload_len, (float*)pkt->payload);
            }
            break;
            case AEC_RESID_SHF_BYPASS:
            {
                memcpy(&aec_state->bypass, pkt->payload, sizeof(aec_state->bypass));

                SHF_Sync_bypass_with_remote((int8_t)aec_state->bypass); // Sync with remote
            }
            break;
            case AEC_RESID_AEC_RESET_MIN_IDLE_TIME:
            {
                aec_state->min_idle_time_ticks = SHF_FRAME_TIME_TICKS;
            }
            break;
// RESID_X_NUM_VALUES is a macro, but RESID_X is an enum member so can't #ifdef
#ifdef AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSAZIMUTH_VALUES:
            {
                float azimuths[BECLEAR_NUMBER_OF_BEAMS];
                float elevation[BECLEAR_NUMBER_OF_BEAMS];
                // Read the current elevation angles, as we need to set azimuth and elevation values at the same time
                SHF_Get_fixed_beams_azimuths(azimuths, elevation, BECLEAR_NUMBER_OF_BEAMS);
                SHF_Set_fixed_beams_azimuths(pkt->payload, elevation, BECLEAR_NUMBER_OF_BEAMS);
            }
            break;
#endif
#ifdef AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSELEVATION_VALUES:
            {
                float azimuths[BECLEAR_NUMBER_OF_BEAMS];
                float elevation[BECLEAR_NUMBER_OF_BEAMS];
                // Read the current azimuths, as we need to set azimuth and elevation values at the same time
                SHF_Get_fixed_beams_azimuths(azimuths, elevation, BECLEAR_NUMBER_OF_BEAMS);
                SHF_Set_fixed_beams_azimuths(azimuths, pkt->payload, BECLEAR_NUMBER_OF_BEAMS);
            }
            break;
#endif
#ifdef AEC_RESID_AEC_FIXEDBEAMSGATING_NUM_VALUES
            case AEC_RESID_AEC_FIXEDBEAMSGATING:
            {
                memcpy(&aec_state->fixed_beams_gated, pkt->payload, sizeof(aec_state->fixed_beams_gated));
            }
            break;
#endif
            default:
            {
                xassert(0);
            }
            break;
            }
        }
    }
}

void process_pp_control_command(control_pkt_t *pkt, pp_state_t * pp_state)
{
    static uint8_t nlmodel_band_index = 0;

    debug_printf("PP Received %d command!!\n",pkt->cmd_id);
    uint8_t cmd = CONTROL_CMD_CLEAR_READ(pkt->cmd_id);
    if(SHF_Is_SHF_command_index(cmd))
    {
        if (IS_CONTROL_CMD_READ(pkt->cmd_id)) {
            SHF_GetPar_PP(cmd, &pkt->payload[0]);
        }
        else {
            SHF_SetPar_PP(cmd, &pkt->payload[0]);
        }
    }
    else
    {
        if (IS_CONTROL_CMD_READ(pkt->cmd_id))
        {
            if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL_NROW_NCOL)
            {
                size_t NRowCol[2];

                SHF_GetNLModelSize_PP(nlmodel_band_index, &NRowCol[0], &NRowCol[1]);

                xassert(NRowCol[0] <= MAX_NL_MODEL_ROWS);
                xassert(NRowCol[1] <= MAX_NL_MODEL_COLS);
                memcpy(pkt->payload, &NRowCol[0], pkt->payload_len);
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL)
            {
                SHF_Get_NLmodel(nlmodel_band_index, (float*)pkt->payload);
            }
            else if (cmd == PP_RESID_PP_CURRENT_IDLE_TIME)
            {
                memcpy(pkt->payload, &pp_state->idle_time_ticks, sizeof(pp_state->idle_time_ticks));
            }
            else if (cmd == PP_RESID_PP_MIN_IDLE_TIME)
            {
                memcpy(pkt->payload, &pp_state->min_idle_time_ticks, sizeof(pp_state->min_idle_time_ticks));
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL_BAND)
            {
                *((uint8_t*)pkt->payload) = nlmodel_band_index;
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_EQUALIZATION_NUM_BANDS)
            {
                SHF_Get_EQNbands(pkt->payload);
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_EQUALIZATION)
            {
                SHF_Get_EQ((float*)pkt->payload);
            }
            else
            {
                xassert(0);
            }
        }
        else // is a write
        {
            if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL)
            {
                SHF_Set_NLmodel(nlmodel_band_index, (float*)pkt->payload);

            }
            else if (cmd == PP_RESID_PP_RESET_MIN_IDLE_TIME)
            {
                pp_state->min_idle_time_ticks = SHF_FRAME_TIME_TICKS;
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_NLMODEL_BAND)
            {
                nlmodel_band_index = *((uint8_t*)pkt->payload);
            }
            else if (cmd == PP_RESID_SPECIAL_CMD_PP_EQUALIZATION)
            {
                SHF_Set_EQ((float*)pkt->payload);
            }
            else
            {
                xassert(0);
            }
        }
    }
}

void do_aec_control(control_pkt_queue_t *pkt_queue, aec_state_t* aec_state)
{
    static uint32_t disable_control = 0;
    if(disable_control)
    {
        return;
    }

    int32_t num_pkts_processed = 0;
    do
    {
        control_pkt_t *pkt = queue_read_packet(pkt_queue);
        /* code */
        if (pkt != NULL)
        {
            if(pkt->cmd_id == AEC_RESID_TEST_AEC_DISABLE_CONTROL)
            {
                memcpy(&disable_control, pkt->payload, pkt->payload_len);
            }
            else
            {
                debug_printf("SHF do control: processing packet\n");
                process_aec_control_command(pkt, aec_state);
            }

            // Change status to done at the end
            pkt->pkt_status = PKT_DONE;
            pkt_queue->queue_rd_index = (pkt_queue->queue_rd_index + 1) % pkt_queue->depth;
            num_pkts_processed++;
        }
        else {
            break;
        }
    } while (num_pkts_processed != pkt_queue->depth); // We don't process more than the full queue depth

    SHF_Signal_control_done_to_remote_AEC();
}

void do_pp_control(control_pkt_queue_t *pkt_queue, pp_state_t * pp_state)
{
    int32_t num_pkts_processed = 0;
    do
    {
        control_pkt_t *pkt = queue_read_packet(pkt_queue);
        /* code */
        if (pkt != NULL)
        {
            debug_printf("SHF do control: processing packet\n");
            process_pp_control_command(pkt, pp_state);

            // Change status to done at the end
            pkt->pkt_status = PKT_DONE;
            pkt_queue->queue_rd_index = (pkt_queue->queue_rd_index + 1) % pkt_queue->depth;
            num_pkts_processed++;
        }
        else {
            break;
        }
    } while (num_pkts_processed != pkt_queue->depth); // We don't process more than the full queue depth

    SHF_Signal_control_done_to_remote_PP();
}

void bypass_loop(control_pkt_queue_t* ctl_q, chanend_t c_to_aec, pp_state_t * pp_state_p) {
    // buf on the stack so it can reuse the memory that shf uses, note writing
    // 0 to 2kB buff might take some time and it will happen every time bypass is
    // enabled
    float buf[BECLEAR_MAX_NUMBER_OF_MICS][BECLEAR_SAMPLES_PER_FRAME] = {{0}};

    unsigned count = 0; // For debug display message only
    bool bypass = 1;
    uint32_t t0 = get_reference_time();
    do {
        // main follows in_word, matching aec_task
        shf_bypass_main_pp(get_core_burn_status(), buf);

        do_pp_control(ctl_q, pp_state_p);
        count++;
        if(count == 200){
            debug_printf("PP - %d %d\n", pp_state_p->idle_time_ticks, pp_state_p->min_idle_time_ticks);
            count = 0;
        }
        uint32_t pp_exec_time_ticks = get_reference_time() - t0;
        pp_state_p->idle_time_ticks = SHF_FRAME_TIME_TICKS - pp_exec_time_ticks;
        pp_state_p->min_idle_time_ticks = pp_state_p->idle_time_ticks < pp_state_p->min_idle_time_ticks ? pp_state_p->idle_time_ticks : pp_state_p->min_idle_time_ticks;

        bypass = chan_in_word(c_to_aec);

        t0 = get_reference_time();

    } while(bypass);
}

void pp_loop(control_pkt_queue_t* ctl_q, chanend_t c_to_aec, pp_state_t * pp_state_p) {
    unsigned count = 0; // For debug display message only
    bool bypass = 0;
    uint32_t t0 = get_reference_time();
    do {
        // main follows in_word, matching aec_task
        SHF_Main_PP();

        do_pp_control(ctl_q, pp_state_p);
        count++;
        if(count == 200){
            debug_printf("PP - %d %d\n", pp_state_p->idle_time_ticks, pp_state_p->min_idle_time_ticks);
            count = 0;
        }
        uint32_t pp_exec_time_ticks = get_reference_time() - t0;
        pp_state_p->idle_time_ticks = SHF_FRAME_TIME_TICKS - pp_exec_time_ticks;
        pp_state_p->min_idle_time_ticks = pp_state_p->idle_time_ticks < pp_state_p->min_idle_time_ticks ? pp_state_p->idle_time_ticks : pp_state_p->min_idle_time_ticks;

        bypass = chan_in_word(c_to_aec);

        t0 = get_reference_time();
    } while(!bypass);
}

void init_pp_state(pp_state_t * pp_state_p) {

    pp_state_p->min_idle_time_ticks = SHF_FRAME_TIME_TICKS;
    pp_state_p->idle_time_ticks = SHF_FRAME_TIME_TICKS;
}

DEFINE_INTERRUPT_PERMITTED (SETUP_PKT_RECV_INTERRUPTABLE_FUNCTIONS, void, pp_task, chanend_t* shf_pp_chanends, control_pkt_queue_t *control_pkt_queue)
{
    SETSR(XS1_SR_QUEUE_MASK);

    chanend_t c_aec_to_pp = shf_pp_chanends[0];

    void * mem = SHF_GetMemory_PP();

    SHF_Init_PP_split_post(
        mem,
        shf_pp_chanends);

    init_pp_parameters();

    pp_state_t pp_state;
    init_pp_state(&pp_state);

    shf_bypass_init_pp(c_aec_to_pp);

    // from here we split to do shf or bypass. bypass on this thread
    // has a large buffer which is kept on the stack and must persist
    // between frames of data. Therefore pp_loop and bypass loop each
    // contain a loop which loops until bypass state changes.
    bool bypass = chan_in_word(c_aec_to_pp);
    while(1){
        if(!bypass) {
            pp_loop(control_pkt_queue, c_aec_to_pp, &pp_state);
            bypass_loop(control_pkt_queue, c_aec_to_pp, &pp_state);
        } else {
            bypass_loop(control_pkt_queue, c_aec_to_pp, &pp_state);
            pp_loop(control_pkt_queue, c_aec_to_pp, &pp_state);
        }
    }
}


void init_aec_state(aec_state_t * aec_state_p) {

    aec_state_p->micpos[0] = shf_defaults_get_mic_geo()->mic0;
    aec_state_p->micpos[1] = shf_defaults_get_mic_geo()->mic1;
    aec_state_p->micpos[2] = shf_defaults_get_mic_geo()->mic2;
    aec_state_p->micpos[3] = shf_defaults_get_mic_geo()->mic3;

    aec_state_p->bypass = false;

    aec_state_p->min_idle_time_ticks = SHF_FRAME_TIME_TICKS;
    aec_state_p->idle_time_ticks = SHF_FRAME_TIME_TICKS;

    aec_state_p->fixed_beams_gated = false;
}

void aec_task(chanend_t* aec_channels, chanend_t c_audio_to_aec, control_pkt_queue_t *control_pkt_queue){
    SETSR(XS1_SR_QUEUE_MASK);

    chanend_t c_aec_to_pp = aec_channels[0];

    uint32_t aec_exec_time_ticks = 0;

    aec_state_t aec_state;

    doa_smoothing_t doa_ctx = DOA_SMOOTHING_INITIALISER;

#if (FIXED_BEAMS_ENABLED == 1)
    gate_vad_state_t gate_ctx = GATE_VAD_INITIALISER;
#endif

    init_aec_state(&aec_state);

    // Debug
    unsigned count = 0; // For debug display message only
    uint32_t t0 = get_reference_time();

    void * mem = SHF_GetMemory_AEC();

    SHF_Init_AEC_split_post(
        mem,
        aec_state.micpos,
        MIC_ARRAY_TYPE,
        aec_channels);

    init_aec_parameters();

    // using the same channel for both should be fine as in the
    // example for SHF they use the same channel to synchronise
    // the threads between calls to Main. We are doing the same
    // thing.
    shf_bypass_init_aec(c_aec_to_pp);

    while(1){
        do_aec_control(control_pkt_queue, &aec_state);

        // Check execution time of AEC loop including buffer exchange
        aec_exec_time_ticks = get_reference_time() - t0;
        aec_state.idle_time_ticks = SHF_FRAME_TIME_TICKS - aec_exec_time_ticks;
        aec_state.min_idle_time_ticks = aec_state.idle_time_ticks < aec_state.min_idle_time_ticks ? aec_state.idle_time_ticks : aec_state.min_idle_time_ticks;


        // Exchange buffers with audio. This has been measured at around 12 ticks = 120ns
        shf_input_t *shf_input = (shf_input_t *)(uintptr_t)chan_in_word(c_audio_to_aec);
        t0 = get_reference_time();
        uint32_t addr_of_shf_output = (uint32_t)(uintptr_t)(&shf_output_buf[shf_out_buf_num]);
        chan_out_word(c_audio_to_aec, addr_of_shf_output);

        // Flip output buffer if double, else do nothing
        shf_out_buf_num ^= (NUM_SHF_OUTPUT_BUFFERS - 1);
        shf_output_t* this_output_buf = &shf_output_buf[shf_out_buf_num];

        // prepare inputs
        float* mics[BECLEAR_NUMBER_OF_MICS];
        float* spks[BECLEAR_NUMBER_OF_FAR];
        float* qcom[BECLEAR_NUMBER_OF_OUTPUTS];
        float* aecmics[BECLEAR_NUMBER_OF_MICS];
        for(int i = 0; i < BECLEAR_NUMBER_OF_MICS; ++i) {
            mics[i] = &shf_input->mics[i][0];
             // SHF supports overwriting the mic input with the AEC residuals in-place.
             // We take advantage of this to save creating another 4ch*4byte*256sample*2buffer = 8KiB buffer.
            aecmics[i] = &shf_input->mics[i][0];
        }
        for(int i = 0; i < BECLEAR_NUMBER_OF_OUTPUTS; ++i) {
            qcom[i] = &this_output_buf->commsout[i][0];
        }
        for(int i = 0; i < BECLEAR_NUMBER_OF_FAR; ++i) {
            spks[i] = &shf_input->far[i][0];
        }

        chan_out_word(c_aec_to_pp, aec_state.bypass);
        if(!aec_state.bypass) {
            SHF_Main_AEC(
                mics,
                spks,
                qcom,
                aecmics
            );
            SHF_Get_azimuths(this_output_buf->azimuths, this_output_buf->spenergy, AEC_RESID_AEC_AZIMUTH_VALUES_NUM_VALUES);
            this_output_buf->smoothed_azimuth = doa_smoothing(&doa_ctx, this_output_buf->azimuths, this_output_buf->spenergy);
#if (FIXED_BEAMS_ENABLED == 1)
            if (aec_state.fixed_beams_gated)
            {
                fixed_beam_gating(&gate_ctx, BECLEAR_SAMPLES_PER_FRAME, qcom, this_output_buf->spenergy);
            }
#endif
        }
        else {
            shf_bypass_main_aec(
                mics,
                spks,
                qcom,
                aecmics,
                get_core_burn_status()
            );
            memset(this_output_buf->azimuths, 0, sizeof(this_output_buf->azimuths));
            memset(this_output_buf->spenergy, 0, sizeof(this_output_buf->spenergy));
            this_output_buf->smoothed_azimuth = NAN;
        }

        for(int i = 0; i < BECLEAR_NUMBER_OF_OUTPUTS; ++i) {
            for(int j = 0; j < BECLEAR_SAMPLES_PER_FRAME; ++j) {
                qcom[i][j] = MAX(qcom[i][j], BECLEAR_MIN_SAMPLE);
                qcom[i][j] = MIN(qcom[i][j], BECLEAR_MAX_SAMPLE);
                aecmics[i][j] = MAX(aecmics[i][j], BECLEAR_MIN_SAMPLE);
                aecmics[i][j] = MIN(aecmics[i][j], BECLEAR_MAX_SAMPLE);
            }
        }

        count++;
        if(count == 200){
            debug_printf("AEC - %d %d\n", aec_state.idle_time_ticks, aec_state.min_idle_time_ticks);
            count = 0;
        }
    }
}
