// Copyright 2022-2023 XMOS LIMITED.
// This Software is subject to the terms of the XCORE VocalFusion Licence.
/// Defaults used in the default out-of-the-box product

#include "shf_defaults.h"
#include "data_plane_defaults.h"
#include "gpo_servicer_defaults.h"
#include "io_config_servicer_defaults.h"
#include "device_enums.h"

const shf_defaults_mic_geo_t* shf_defaults_get_mic_geo()
{
    static const shf_defaults_mic_geo_t defaults = {
        #include "mic_geometries.h" // Include file autogenerated from yaml files
    };
    return &defaults;
}

const shf_defaults_pp_t* shf_defaults_get_pp()
{
    static const shf_defaults_pp_t defaults = {
        #include "pp_cmds_defaults.h" // Include file autogenerated from yaml files
    };
    return &defaults;
}

const shf_defaults_aec_t* shf_defaults_get_aec()
{

    static const shf_defaults_aec_t defaults = {
        #include "aec_cmds_defaults.h" // Include file autogenerated from yaml files
    };
    return &defaults;
}

const data_plane_defaults_t* data_plane_defaults_get() {
    static const data_plane_defaults_t defaults = {
        #include "audio_cmds_defaults.h" // Include file autogenerated from yaml files
        .mic_init_time_samples = 3333,   // 3333 / 16kHz = 208.3ms, found experimentally for the XK-VOICE-SQ66 EVK
    };
    return &defaults;
}

const gpo_config_t* gpo_config_get() {
    static const gpo_config_t config = {
        #include "gpo_config.h" // Include file autogenerated from yaml files
    };
    return &config;
}

const gpi_config_t* gpi_config_get() {
    static const gpi_config_t config = {
        #include "gpi_config.h" // Include file autogenerated from yaml files
    };
    return &config;
}

