// Copyright 2022-2024 XMOS LIMITED.
// This Software is subject to the terms of the XCORE VocalFusion Licence.

#include <xcore/assert.h> // Needed for xassert()
#include "aec_cmds.h" // Autogenerated
#include "pp_cmds.h" // Autogenerated
#include "shf.h"
#include "app_conf.h" // Needed for BECLEAR_NUMBER_OF_BEAMS
#include "shf_defaults.h"

void init_aec_parameters(void) {
    // have to copy onto stack because the SetPar functions take non const pointers :(
    shf_defaults_aec_t defaults = *shf_defaults_get_aec();
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_HPFONOFF,          &defaults.hpfonoff );
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_AECSILENCELEVEL,   &defaults.aecsilencelevel );
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_AECEMPHASISONOFF,  &defaults.aecemphasisonoff );
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_FAR_EXTGAIN,       &defaults.far_extgain );
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_PCD_COUPLINGI,     &defaults.pcd_couplingi );
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_PCD_MINTHR,        &defaults.pcd_minthr );
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_PCD_MAXTHR,        &defaults.pcd_maxthr );
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_ASROUTONOFF,       &defaults.asroutonoff);
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_ASROUTGAIN,        &defaults.asroutgain );
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_FIXEDBEAMSONOFF,   &defaults.fixedbeamsonoff);
    SHF_SetPar_AEC( BECLEAR_SUPERHANDSFREE_AEC_FIXEDBEAMNOISETHR, &defaults.fixedbeamnoisethr );
    SHF_Set_fixed_beams_azimuths(defaults.fixedbeamsazimuth_values, defaults.fixedbeamselevation_values, BECLEAR_NUMBER_OF_BEAMS);
}

void init_pp_parameters(void) {
    // have to copy onto stack because the SetPar functions take non const pointers :(
    shf_defaults_pp_t defaults = *shf_defaults_get_pp();
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_AGCONOFF,          &defaults.agconoff );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_AGCMAXGAIN,        &defaults.agcmaxgain );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_AGCDESIREDLEVEL,   &defaults.agcdesiredlevel );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_AGCGAIN,           &defaults.agcgain );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_AGCTIME,           &defaults.agctime );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_AGCFASTTIME,       &defaults.agcfasttime );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_AGCALPHAFASTGAIN,  &defaults.agcalphafastgain );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_AGCALPHASLOW,      &defaults.agcalphaslow );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_AGCALPHAFAST,      &defaults.agcalphafast );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_LIMITONOFF,        &defaults.limitonoff );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_LIMITPLIMIT,       &defaults.limitplimit );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_MIN_NS,            &defaults.min_ns );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_MIN_NN,            &defaults.min_nn );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_ECHOONOFF,         &defaults.echoonoff );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_GAMMA_E,           &defaults.gamma_e );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_GAMMA_ETAIL,       &defaults.gamma_etail );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_GAMMA_ENL,         &defaults.gamma_enl );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_NLATTENONOFF,      &defaults.nlattenonoff );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_NLAEC_MODE,        &defaults.nlaec_mode );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_MGSCALE,           &defaults.mgscale );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_FMIN_SPEINDEX,     &defaults.fmin_speindex );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_DTSENSITIVE,       &defaults.dtsensitive );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_ATTNS_MODE,        &defaults.attns_mode );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_ATTNS_NOMINAL,     &defaults.attns_nominal );
    SHF_SetPar_PP( BECLEAR_SUPERHANDSFREE_PP_ATTNS_SLOPE,       &defaults.attns_slope );

    int rows, cols;
    SHF_Set_NLmodel(0, shf_defaults_get_nlmodel_all(&rows, &cols));
    int bands;
    SHF_Set_EQ(shf_defaults_get_eq_filter_all(&bands));
    xassert(bands==WB_EQ_BANDS);
}
