"""Actual end-to-end profiles on the fixed36-scene panel. README_S6A_PROBES.md."""
from __future__ import annotations
import argparse
import concurrent.futures
import json
import os
from pathlib import Path
import subprocess
import threading
import time
import psutil
from s6a_common import *
from s6a_baseline import same_process
from s4_h2_run import fixed_gain_copy, completed_session
from s45_h2_run import verify_native_completion

def prepare():
    target=REPORT/'PROBE_JOB_MANIFEST_V2.json'
    if target.exists():
        result=read(target)
        for row in result['execution_code']:bind(row['path'],row['sha256'])
        return result
    panel=read(REPORT/'PROBE_PANEL.json');profile_index=read(REPORT/'profiles/PROFILE_INDEX.json')
    delivery=read(REPORT/'CUE_DELIVERY_INDEX.json')
    # Delivery index is explicitly generated by a separate input-only adapter.
    rows=delivery.get('rows',delivery.get('scenes',[]))
    cue_by_case={row['case_id']:row for row in rows}
    jobs=[];inputs=[]
    execution_code=[bind(p) for p in sorted((H2/'app/edge_speech_pipeline').glob('*.py'))]
    execution_code += [bind(__file__)]+[bind(SIM/'scripts'/name) for name in
        ('s6a_common.py','s6a_baseline.py','s4_common.py','s5_common.py','s4_h2_run.py','s45_h2_run.py')]
    basejobs=[j for j in read(REPORT/'JOB_MANIFEST.json')['jobs'] if j['case_id'] in panel['case_ids']]
    assert len(basejobs)==72 and len(profile_index)==10
    for base in basejobs:
        cid,out=base['case_id'],base['stream']
        bind(base['raw_audio']['path'],base['raw_audio']['sha256'])
        adapter_path=PAYLOAD/'probe_inputs'/cid/(out+'.wav')
        adapter_path.parent.mkdir(parents=True,exist_ok=True)
        adapter=fixed_gain_copy(base['raw_audio']['path'],adapter_path,base['gain'])
        inputs.append({'case_id':cid,'stream':out,'raw':base['raw_audio'],'adapter':adapter})
        for spec in profile_index:
            pb=bind(spec['file_binding']['path'],spec['file_binding']['sha256']);profile=read(pb['path'])
            assert stable_hash(profile)==spec['profile_sha256']
            assert profile['input']['gain']==1 and profile['input']['already_gained']
            cb=None
            if profile['xvf']['mode']!='none':
                row=cue_by_case[cid]
                cb=row.get('sanitized')
                if cb is None:raise ValueError('Unknown sanitized telemetry binding schema')
                cb=bind(cb['path'],cb['sha256'])
            identity={'profile':pb,'audio':adapter['output_binding'],'raw_audio':base['raw_audio'],'gain_once':base['gain'],
                'telemetry':cb,'code':execution_code,'assets':read(S5/'execution_contract.json')['baseline']['scientific_config']['assets'],
                'provider':'CPUExecutionProvider/cpu','process_lifecycle':'fresh full actual application','schema':'s6a_profile_run_v2'}
            key=stable_hash(identity);profile_id=profile['profile_id']
            jobs.append({'case_id':cid,'stream':out,'profile_id':profile_id,'job_key':key,'identity':identity,'profile':pb,
                'telemetry':cb,'input_audio':adapter['output_binding'],'adapter':adapter,'raw_audio':base['raw_audio'],
                'report_dir':str(REPORT/'probes_v2'/profile_id/cid/out),'payload_root':str(PAYLOAD/'probes_v2'/profile_id/cid/out)})
    # Pair outputs/controls within each scene; thread scheduling is separately recorded.
    jobs.sort(key=lambda j:(panel['case_ids'].index(j['case_id']),j['profile_id'],j['stream']))
    value={'schema':'jp_s6a_probe_jobs_v2','created_utc':now(),'jobs':jobs,'requested':720,'scene_count':36,'profiles':10,
        'panel':bind(REPORT/'PROBE_PANEL.json'),'execution_code':execution_code,'input_adapters':inputs,
        'cache_semantics':'Complete exact execution identity required. Component/audio/endpoint/decoder mutations run fresh actual neural/stateful inference; no old word slicing.',
        'panel_and_profile_values_frozen_before_new_panel_outcomes':True,
        'implementation_revision':'v2 fixes causal transcript overlap display and profile validation; named settings unchanged; 48 v1 jobs preserved and excluded',
        'superseded_revision_receipt':bind(REPORT/'PROBE_V1_CLOSURE.json'),
        'candidate_confirmation':'S6A screening only; no general winner promoted before full240 confirmation inS6B/C'}
    save(target,value);return value

def run_job(job):
    folder=Path(job['report_dir']);folder.mkdir(parents=True,exist_ok=True);rp=folder/'run_receipt.json'
    if rp.exists():
        receipt=read(rp)
        if receipt['status']=='COMPLETE':
            assert receipt['job_key']==job['job_key'] and receipt['identity']==job['identity']
            for field in ('events_binding','session_summary_binding','metrics_binding','resources_binding'):bind(receipt[field]['path'],receipt[field]['sha256'])
            verify_native_completion(Path(receipt['session_dir']),Path(job['input_audio']['path']))
            return {'case_id':job['case_id'],'stream':job['stream'],'profile_id':job['profile_id'],'status':'COMPLETE_REUSED','receipt':bind(rp),'model_wall_s':0}
    if not launch_allowed(360) or (REPORT/'STOP_REQUEST.json').exists():return {'case_id':job['case_id'],'stream':job['stream'],'profile_id':job['profile_id'],'status':'PENDING_BUDGET'}
    attempts=[read(p) for p in sorted(folder.glob('attempt_*/attempt_receipt.json'))]
    for attempt in attempts:
        if attempt.get('owned_process_pid') and same_process(attempt['owned_process_pid'],attempt['owned_process_creation_time']):
            raise RuntimeError('Exact prior probe child still active')
    for attempt in attempts:
        if attempt['status']=='COMPLETE':save(rp,attempt);return run_job(job)
    for number in range(len(attempts)+1,3):
        resources()
        af=folder/('attempt_'+str(number));payload=Path(job['payload_root'])/('attempt_'+str(number));af.mkdir();payload.mkdir(parents=True)
        root=payload/'empty_data';root.mkdir()
        argv=[str(EDGE_PYTHON),'-m','app.edge_speech_pipeline','file',job['input_audio']['path'],'--accelerated','--research-profile',job['profile']['path']]
        if job['telemetry']:argv+=['--research-telemetry',job['telemetry']['path']]
        env=single_thread_env();env['EDGE_SPEECH_DATA_ROOT']=str(root);env.pop('EDGE_SPEECH_ASSET_ROOT',None)
        receipt={'status':'STARTED','job_key':job['job_key'],'identity':job['identity'],'case_id':job['case_id'],'stream':job['stream'],
            'profile_id':job['profile_id'],'attempt_number':number,'argv':argv,'created_utc':now(),'raw_audio':job['raw_audio'],'adapter':job['adapter'],
            'input_audio':job['input_audio'],'initial_gallery_files':0,'truth_fields_sent_to_predictor':False,'hardware_invocations':0}
        ar=af/'attempt_receipt.json';save(ar,receipt);process=None;creation=None;started=time.monotonic();samples=[]
        try:
            for b in (job['profile'],job['input_audio'],job['telemetry']):
                if b:bind(b['path'],b['sha256'])
            with (af/'stdout.jsonl').open('wb') as out,(af/'stderr.txt').open('wb') as err:
                process=subprocess.Popen(argv,cwd=H2,env=env,stdout=out,stderr=err,creationflags=getattr(subprocess,'CREATE_NO_WINDOW',0))
                creation=psutil.Process(process.pid).create_time();receipt.update(owned_process_pid=process.pid,owned_process_creation_time=creation);save(ar,receipt)
                while process.poll() is None:
                    try:process.wait(timeout=2)
                    except subprocess.TimeoutExpired:pass
                    if time.monotonic()-started>360:raise TimeoutError('Probe child360s')
                    if process.poll() is None and same_process(process.pid,creation):
                        parent=psutil.Process(process.pid);tree=[parent]+parent.children(recursive=True);row=[]
                        for proc in tree:
                            memory=proc.memory_full_info();row.append({'pid':proc.pid,'creation_time':proc.create_time(),'rss':memory.rss,
                                'uss':getattr(memory,'uss',None),'private_commit':getattr(memory,'private',None),'pss':getattr(memory,'pss',None)})
                        samples.append({'elapsed_s':time.monotonic()-started,'processes':row,'available_ram_bytes':psutil.virtual_memory().available})
                        assert sum(r['rss'] for r in row)<40*2**30 and psutil.virtual_memory().available>=8*2**30
            assert process.returncode==0,'Research application failed; inspect preserved stderr'
            session=completed_session(root);assert session is not None
            completion=verify_native_completion(session,Path(job['input_audio']['path']))
            summary=read(session/'session_summary.json');assert summary['research']['profile']==read(job['profile']['path'])
            assert summary['research']['effective_config']['input_gain']==1.0
            for key in ('audio_frames_dropped','portaudio_input_overflows','raw_capture_reserve_failures'):
                assert key in summary['telemetry'] and summary['telemetry'][key]==0
            events=[json.loads(line) for line in (session/'events.jsonl').read_text(encoding='utf-8').splitlines() if line.strip()]
            assert sum(e['event_type']=='research_effective_config' for e in events)==1
            finals=[dict(source_cursor_s=e['source_time_sec'],**e['payload']) for e in events if e['event_type']=='transcript_final']
            metrics={'state':'COMPLETED','failure_events':[],'telemetry':summary['telemetry'],'final_transcripts':finals}
            save(af/'metrics.json',metrics)
            receipt.update(status='COMPLETE',exit_code=process.returncode,session_dir=str(session),completion_evidence=completion,
                session_summary_binding=bind(session/'session_summary.json'),events_binding=bind(session/'events.jsonl'),metrics_binding=bind(af/'metrics.json'),
                model_success_has_internal_asset_validation=True,audio_duration_s=job['adapter']['duration_s'])
        except BaseException as exc:
            receipt.update(status='FAILED',error=repr(exc))
            if isinstance(exc,(KeyboardInterrupt,SystemExit)):raise
        finally:
            if process is not None and process.poll() is None:
                if creation is None or same_process(process.pid,creation):
                    process.terminate()
                    try:process.wait(timeout=10)
                    except subprocess.TimeoutExpired:
                        if creation is None or same_process(process.pid,creation):process.kill();process.wait(timeout=10)
            receipt.update(model_wall_s=time.monotonic()-started,completed_utc=now(),owned_child_alive=bool(process and process.poll() is None))
            save(af/'resource_samples.json',{'rows':samples,'scope':'USS private resident and RSS upper bound; Windows private_commit is not resident; PSS may be unavailable','paced':False})
            receipt['resources_binding']=bind(af/'resource_samples.json');save(ar,receipt)
        if receipt['status']=='COMPLETE':
            save(rp,receipt)
            return {'case_id':job['case_id'],'stream':job['stream'],'profile_id':job['profile_id'],'status':'COMPLETE','receipt':bind(rp),'model_wall_s':receipt['model_wall_s']}
    save(rp,{'status':'FAILED','job_key':job['job_key'],'identity':job['identity'],'attempt_receipts':[bind(p) for p in folder.glob('attempt_*/attempt_receipt.json')]})
    return {'case_id':job['case_id'],'stream':job['stream'],'profile_id':job['profile_id'],'status':'FAILED','receipt':bind(rp)}

def run(workers=2,limit=None):
    import msvcrt
    spec=prepare();jobs=spec['jobs']
    if limit:jobs=jobs[:limit]
    rows=[];new_wall=0;new_n=0
    with (REPORT/'probe_coordinator.lock').open('a+b') as lease:
        lease.seek(0)
        if not lease.read(1):lease.write(b'0');lease.flush()
        lease.seek(0);msvcrt.locking(lease.fileno(),msvcrt.LK_NBLCK,1)
        try:
            save(REPORT/'PROBE_COORDINATOR.json',{'pid':os.getpid(),'creation_time':psutil.Process().create_time(),'workers':workers,'utc':now()})
            with Progress('COMPONENT_PROBES',len(jobs)) as progress,concurrent.futures.ThreadPoolExecutor(max_workers=workers) as pool:
                pending={};iterator=iter(jobs)
                for _ in range(workers):
                    job=next(iterator,None)
                    if job:pending[pool.submit(run_job,job)]=job
                while pending:
                    done,_=concurrent.futures.wait(pending,return_when=concurrent.futures.FIRST_COMPLETED)
                    for f in done:
                        pending.pop(f);row=f.result();rows.append(row);progress.done+=1
                        if row['status']=='COMPLETE':new_n+=1;new_wall+=row['model_wall_s']
                        progress.detail={'fresh_complete':new_n,'cache_hits':sum(r['status']=='COMPLETE_REUSED' for r in rows),
                            'failed':sum(r['status']=='FAILED' for r in rows),'summed_child_wall_s':new_wall,
                            'fresh_remaining_eta_s':(len(jobs)-len(rows))*new_wall/new_n/workers if new_n else None,'workers':workers}
                        save(REPORT/'PROBE_PROGRESS_ROWS.json',{'rows':rows,'utc':now()})
                        if sum(r['status']=='FAILED' for r in rows)>=2:raise RuntimeError('Two failed probe jobs; diagnose before expansion')
                        if not launch_allowed(360) or (REPORT/'STOP_REQUEST.json').exists():
                            progress.detail['new_launches_stopped']=True
                            continue
                        job=next(iterator,None)
                        if job:pending[pool.submit(run_job,job)]=job
            complete=sum(r['status'].startswith('COMPLETE') for r in rows)
            save(REPORT/'PROBE_EXECUTION_RECEIPT.json',{'status':'COMPLETE' if complete==720 else 'PARTIAL_RESUMABLE','requested':720,
                'examined_this_invocation':len(rows),'complete_this_invocation':complete,'workers':workers,'rows':rows,'utc':now(),'fresh_child_wall_s':new_wall})
        finally:
            save(REPORT/'PROBE_CLEANUP.json',{'utc':now(),'coordinator_pid':os.getpid(),'creation_time':psutil.Process().create_time(),'worker_pool_joined':True,'hardware_invocations':0})
            lease.seek(0);msvcrt.locking(lease.fileno(),msvcrt.LK_UNLCK,1)

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--workers',type=int,default=2);parser.add_argument('--limit',type=int)
    args=parser.parse_args();assert 1<=args.workers<=4
    run(args.workers,args.limit)
