#**********************
# Gather Sources
#**********************

file(GLOB APP_SOURCES_COMMON src/user_config/*.c)

# We will give different compiler switches for this timing critical code
file(GLOB APP_SOURCES_DATA_PLANE   src/user_dsp/*.c src/default_params/init_shf_parameters.c)
list(APPEND APP_SOURCES_COMMON ${APP_SOURCES_DATA_PLANE})

set(APP_INCLUDES
    src
    src/default_params
)

#*********************************
# Find correct Python installation
#*********************************

set(Python3_FIND_FRAMEWORK NEVER)
set(Python3_FIND_VIRTUALENV ONLY)
find_package(Python3 REQUIRED)

#*******************************************
# Create object library for SHF memory data
#*******************************************

set(SHF_MEM_OBJ shf_mem_data)
add_library(${SHF_MEM_OBJ} OBJECT ${CMAKE_INSTALL_PREFIX}/precompiled/xshf/src/BeClearMemory.S)
target_include_directories(${SHF_MEM_OBJ}
    PUBLIC
    ${CMAKE_INSTALL_PREFIX}/precompiled/xshf/inc
)

#**********************
# Flags
#**********************
set(APP_COMPILER_FLAGS_COMMON
    -g
    -report
    -fxscope
    -mcmodel=large
    # -Werror
    -Wall
    -Wno-xcore-fptrgroup
    ${CMAKE_CURRENT_LIST_DIR}/src/config.xscope
)


set(APP_COMPILER_FLAGS
    -Os
    ${APP_COMPILER_FLAGS_COMMON}
)

set(APP_COMPILER_FLAGS_DATA_PLANE
    -O3
    -mno-dual-issue
)
list(JOIN APP_COMPILER_FLAGS_DATA_PLANE " " APP_COMPILER_FLAGS_DATA_PLANE) #Turn into string
set_source_files_properties(${APP_SOURCES_DATA_PLANE}  PROPERTIES COMPILE_FLAGS "${APP_COMPILER_FLAGS_DATA_PLANE}")

option(RESERVE_USER_MEMORY "If set 17 kB is reserved in the build" OFF)

set(APP_COMPILE_DEFINITIONS_COMMON
    DEBUG_PRINT_ENABLE=1
    PLATFORM_USES_TILE_0=1
    PLATFORM_USES_TILE_1=1
    PLATFORM_SUPPORTS_TILE_0=1
    PLATFORM_SUPPORTS_TILE_1=1
    # NDEBUG=1 #Turns off asserts
    USE_EP_PROXY=1
    EP0_TILE_NO=1
    XASSERT_ENABLE_DEBUG=1
    XASSERT_ENABLE_ASSERTIONS=1
    XASSERT_ENABLE_LINE_NUMBERS=1
)
if(RESERVE_USER_MEMORY)
    list(APPEND APP_COMPILE_DEFINITIONS_COMMON RESERVE_USER_MEMORY=1)
else()
    list(APPEND APP_COMPILE_DEFINITIONS_COMMON RESERVE_USER_MEMORY=0)
endif()


set(APP_LINK_OPTIONS
    -lquadspi
    -report
    ${CMAKE_CURRENT_LIST_DIR}/src/config.xscope
    -Wm,--first,$<TARGET_OBJECTS:${SHF_MEM_OBJ}>
    -Wm,--wno226 # Disable warnings for not connected ports
)

set(APP_COMMON_LINK_LIBRARIES
    fwk_xvf::xvf
    fwk_xvf::doa_smoothing
    fwk_xvf::bsp_config::dac::dac3101
    otp3
    ${SHF_MEM_OBJ}
)

#*********************************************************
# Autogenerate files from the cmds .yaml file
#*********************************************************
set( AUTOGEN_DIR ${CMAKE_CURRENT_BINARY_DIR}/src.autogen )
set( YAML_DIR autogeneration/yaml_files)

# Four output folders - device, host, common, and the documentation directory.
set( AUTOGEN_COMMON ${AUTOGEN_DIR}/common )
set( AUTOGEN_HOST ${AUTOGEN_DIR}/host )
set( AUTOGEN_DEVICE ${AUTOGEN_DIR}/device )
set( AUTOGEN_DOCS ../doc/autogenerated)
cmake_path(ABSOLUTE_PATH AUTOGEN_DOCS NORMALIZE)

# Set up keywords to make writing the Python incantations clearer
set( YAML_COMMANDS_DIR ${YAML_DIR}/control_commands )
set( YAML_SETTINGS_DIR ${YAML_DIR}/settings_and_defaults )
cmake_path(ABSOLUTE_PATH YAML_COMMANDS_DIR NORMALIZE)
cmake_path(ABSOLUTE_PATH YAML_SETTINGS_DIR NORMALIZE)

execute_process(
    COMMAND ${Python3_EXECUTABLE} -m yaml_autogen
    OUTPUT_VARIABLE YAML_AUTOGEN_TEMPLATES_LOCATION_PY
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE YAML_AUTOGEN_RESULT
)
if(NOT YAML_AUTOGEN_RESULT EQUAL 0)
    message(FATAL_ERROR "yaml_autogen not found by python, have you used pip to install requirements_build.txt?")
endif()

set( YAML_TEMPLATES_CMD ${YAML_AUTOGEN_TEMPLATES_LOCATION_PY}/command_map)
set( YAML_TEMPLATES_DOC ${YAML_AUTOGEN_TEMPLATES_LOCATION_PY}/documentation)
set( YAML_TEMPLATES_DEFAULTS ${YAML_AUTOGEN_TEMPLATES_LOCATION_PY}/defaults)
set( YAML_TEMPLATES_ENUM ${YAML_AUTOGEN_TEMPLATES_LOCATION_PY}/enums)

set( YAML_PROC_GENERIC   yaml_autogen.outputs.generic_process )
set( YAML_PROC_DEFAULTS  yaml_autogen.outputs.default_values )
set( YAML_PROC_DOCS      yaml_autogen.outputs.documentation )
set( YAML_PROC_ENUM      yaml_autogen.outputs.enum_consumers )
set( YAML_PROC_MULTI     yaml_autogen.outputs.multiple_command_input )



#******************************************************************
# Autogenerate the nl model .c files from the nl model binary files
#******************************************************************
set(NL_MODEL_AUTOGEN_DIR ${CMAKE_CURRENT_BINARY_DIR}/nlmodel_src.autogen )
set(NL_MODEL_BIN_DIR ${CMAKE_CURRENT_SOURCE_DIR}/nl_model_gen/nlmodel_bin/)
set(NL_MODEL_C_DIR ${NL_MODEL_AUTOGEN_DIR})

#********************************************************************
# Autogenerate the eq filter .c files from the eq filter binary files
#********************************************************************
set(EQ_FILTER_AUTOGEN_DIR ${CMAKE_CURRENT_BINARY_DIR}/eq_filter_src.autogen )
set(EQ_FILTER_BIN_DIR ${CMAKE_CURRENT_SOURCE_DIR}/eq_filter_gen/eq_filter_bin/)
set(EQ_FILTER_C_DIR ${EQ_FILTER_AUTOGEN_DIR})

#**********************
# Build profiles
#**********************

# To set up a new build configuration, choose one of each of the following.
# Construct an appropriate build profile name using the parameter names, in order.
# For example, an INT Device, 48kHz in and out, linear build, the build profile name will be
#     intdev-io48-pnone-lin
# Add this to the BUILD_PROFILES variable below.
# This will automagically be converted into a set of build profiles.

#   ----- Device config ------
#    INT Device    | intdev
#    USB           | usb
#   ----- I2S rate -----           < intdev only
#    16 kHz        | -lr16
#    48 kHz        | -lr48
#   ----- USB rate -----           < ua only
#    16 kHz        | -io16
#    48 kHz        | -io48
#   ----- Microphone geometry -----
#    Linear        | -lin
#    Squarecular   | -sqr
#   ----- Control mode -----
#    SPI           | -spi
#    I2C           | -i2c
#   ----- Disable MCLK drive ----- < int only
#    Don't drive   | -extmclk

# To create a new configurable parameter, add a entry in the table above
# and modify the build name parser, located below.
#
# Special builds:
#
# None
#

set(BUILD_PROFILES
    # INT Device, 16 and 48kHz, both control modes, lin and sqr geo, with and without extmclk operation
    "intdev-lr16-lin-spi"
    "intdev-lr16-sqr-spi"
    "intdev-lr16-lin-i2c"
    "intdev-lr16-sqr-i2c"
    "intdev-lr48-lin-spi"
    "intdev-lr48-sqr-spi"
    "intdev-lr48-lin-i2c"
    "intdev-lr48-lin-i2c-spatial"
    "intdev-lr48-sqr-i2c"
    "intdev-lr16-lin-spi-extmclk"
    "intdev-lr16-sqr-spi-extmclk"
    "intdev-lr16-lin-i2c-extmclk"
    "intdev-lr16-sqr-i2c-extmclk"
    "intdev-lr48-lin-i2c-extmclk"
    "intdev-lr48-sqr-i2c-extmclk"
    "intdev-lr48-lin-spi-extmclk"
    "intdev-lr48-sqr-spi-extmclk"
    "intdev-lr48-sqr-spi-fixedbeam"
    "intdev-lr48-sqr-i2c-fixedbeam"

    # INT Host, 16 and 48kHz, both control modes, lin and sqr geo
    "inthost-lr16-lin-spi"
    "inthost-lr16-sqr-spi"
    "inthost-lr16-lin-i2c"
    "inthost-lr16-sqr-i2c"
    "inthost-lr48-lin-spi"
    "inthost-lr48-sqr-spi"

    # UA variants
    "ua-io16-lin"
    "ua-io48-lin"
    "ua-io48-lin-io-exp"
    "ua-io16-sqr"
    "ua-io48-sqr"
    "ua-io48-lin-spatial"
    "ua-io48-sqr-fixedbeam"

)

# Add instructions for extra build configs
if(EXISTS  ${CMAKE_CURRENT_LIST_DIR}/extra-configs.cmake)
    include("extra-configs.cmake")
endif()

# The goal is to produce a single variable BUILD_PROFILES containing a list of all valid build profile names,
#     BUILD_PROFILES == "intdev-lr16-lin-spi;ua-io48-sqr; [...]"

# Each build profile will automagically then have a BUILD_OPTS variable listing all compile definitions for that build profile created
#     BUILD_OPTS_intdev-lr16-lin-spi == "INT_DEVICE=1;appconfLRCLK_NOMINAL_HZ=16000;[...]"

# This is done by the following build name parser.

# Full build profile name is currently
#     DEVICE_CONFIG[-I2S_RATE][-USB_SAMPLE_RATE]-MIC_GEOMETRY[-CONTROL_TRANSPORT]
# Special build names, such as
#     demo
# are permitted; custom logic must be written for each of these as required.

macro(add_to_build_opts OPTION_STRING)
    list(APPEND BUILD_OPTS_${PROFILE} ${OPTION_STRING})
endmacro()

macro(add_to_build_sources OPTION_STRING)
    list(APPEND BUILD_SOURCES_${PROFILE} ${OPTION_STRING})
endmacro()
macro(add_to_build_libs OPTION_STRING)
    list(APPEND BUILD_LIBS_${PROFILE} ${OPTION_STRING})
endmacro()

foreach(PROFILE ${BUILD_PROFILES})

    set(PRODUCT_DEFAULT_SPECIFIER product)

    # - Device config -
    if (PROFILE MATCHES "^intdev")
        add_to_build_opts("INT_DEVICE=1")
    elseif (PROFILE MATCHES "^inthost")
        add_to_build_opts("INT_HOST=1")
    elseif (PROFILE MATCHES "^ua")
        add_to_build_opts("UA=1")
        set(messaging_USB 1)
        # When USB is added, add the appropriate commands here
    else()
        message(STATUS "Build profile '${PROFILE}' does not match a DEVICE_CONFIG - continuing...")
    endif()

    # - I2S sample rates -
    set(LRCLK_RATE)
    if (PROFILE MATCHES "-lr(16|48)")
        set(LRCLK_RATE ${CMAKE_MATCH_1})
    elseif(PROFILE MATCHES "-io(16|48)")
        set(LRCLK_RATE ${CMAKE_MATCH_1})
    endif()

    if(LRCLK_RATE)
        if(LRCLK_RATE MATCHES "16")
            add_to_build_opts("PRODUCT_ID=PRODUCT_ID_IO_16KHZ")
        elseif(LRCLK_RATE MATCHES "48")
            add_to_build_opts("PRODUCT_ID=PRODUCT_ID_IO_48KHZ")
        else()
            message(STATUS "Build profile '${PROFILE}' does not match a supported USB sample rate - continuing...")
        endif()
        add_to_build_opts("appconfLRCLK_NOMINAL_HZ=${LRCLK_RATE}000")
        add_to_build_opts("appconfUSB_IN_OUT_NOMINAL_HZ=${LRCLK_RATE}000")
    else()
        message(STATUS "Build profile '${PROFILE}' does not match a supported audio sample rate - continuing...")
    endif()
    unset(LRCLK_RATE)

    # - Mic geometry -
    if (PROFILE MATCHES "-sqr")
        add_to_build_opts("MIC_ARRAY_TYPE_LIN=0")
        add_to_build_opts("MIC_ARRAY_TYPE_SQR=1")
    else()
        # Use linear geometry by default
        add_to_build_opts("MIC_ARRAY_TYPE_LIN=1")
        add_to_build_opts("MIC_ARRAY_TYPE_SQR=0")
    endif()

    # - Control mode -
    if (PROFILE MATCHES "-spi")
        add_to_build_opts("appconfSPI_CTRL_ENABLED=1")
        add_to_build_opts("appconfI2C_CTRL_ENABLED=0")
    elseif (PROFILE MATCHES "-i2c")
        add_to_build_opts("appconfSPI_CTRL_ENABLED=0")
        add_to_build_opts("appconfI2C_CTRL_ENABLED=1")
    elseif (PROFILE MATCHES "ua")
        add_to_build_opts("appconfSPI_CTRL_ENABLED=0")
        add_to_build_opts("appconfI2C_CTRL_ENABLED=0")
        add_to_build_opts("appconfUSB_CTRL_ENABLED=1")
    else()
        message(STATUS "Build profile '${PROFILE}' does not match a CONTROL_MODE - continuing...")
    endif()

    # - IO expander -
    if (PROFILE MATCHES "-io-exp")
        add_to_build_opts("IO_EXPANDER_ENABLED=1")
    endif()

    # Disable internal mclk generation
    if (PROFILE MATCHES "-extmclk")
        add_to_build_opts("appconfEXTERNAL_MCLK=1")
        if(NOT PROFILE MATCHES "intdev")
            message(FATAL_ERROR "Build profile '${PROFILE}' specifies use of external mclk for build other than intdev")
        endif()
    else()
        # Use defaults - do nothing
    endif()

    # Special builds
    # First check if we need to configure extra builds
    set(EXTRA_BUILD_INCLUDED OFF)
    set(NL_MODEL_BIN "")
    set(EQ_FILTER_BIN "")
    set(VERSION_SET OFF)
    if(EXISTS ${CMAKE_CURRENT_LIST_DIR}/extra-configs.cmake)
        add_extra_builds()
    endif()

    # Special build to demo panning the auto select beam
    # onto the stereo output of XVF3800
    if (PROFILE MATCHES "-spatial")
        set(EXTRA_BUILD_INCLUDED ON)
        set(PRODUCT_DEFAULT_SPECIFIER spatial)
        add_to_build_opts("appconfSPATIAL=1")
        add_to_build_libs(fwk_xvf::pan_pot)
        add_to_build_libs(fwk_xvf::bsp_config::xk_voice_sq66_evk)
        add_to_build_opts("appconfUSER_CONFIG_ENABLED=1")
    endif()

    if (PROFILE MATCHES "-fixedbeam")
        add_to_build_opts("FIXED_BEAMS_ENABLED=1")
        set(PRODUCT_DEFAULT_SPECIFIER fixed_beam)
    endif()

    if(NOT VERSION_SET)
        add_to_build_opts("VERSION_MAJOR=${DEFAULT_VERSION_MAJOR}")
        add_to_build_opts("VERSION_MINOR=${DEFAULT_VERSION_MINOR}")
        add_to_build_opts("VERSION_PATCH=${DEFAULT_VERSION_PATCH}")
    endif()

    if(NOT EXTRA_BUILD_INCLUDED)
        # Use this to add default build sources
        add_to_build_libs(fwk_xvf::bsp_config::xk_voice_sq66_evk)
        add_to_build_opts("appconfUSER_CONFIG_ENABLED=1")
    endif()

    add_to_build_sources(src/default_params/defaults.c)

    # Set NL model and include it in the build
    if (NL_MODEL_BIN STREQUAL "")
        if (EXISTS ${NL_MODEL_BIN_DIR}/nlmodel_buffer_override.bin.r16.c40)
            message("Found NL model override!")
            set(NL_MODEL_BIN nlmodel_buffer_override.bin.r16.c40)
        else()
            set(NL_MODEL_BIN nlmodel_buffer_default.bin.r16.c40)
        endif()
    endif()

    string(REGEX REPLACE "[.]bin[.]r16[.]c40$" ".c" NL_MODEL_C ${NL_MODEL_BIN})
    # Generate NL model C file from the .bin file
    unset(NL_MODEL_GEN_ARGS)
    set(NL_MODEL_C_PATH ${NL_MODEL_C_DIR}/${NL_MODEL_C})
    list(APPEND NL_MODEL_GEN_ARGS --out-file ${NL_MODEL_C_PATH} --append-str all --depfile ${NL_MODEL_C_PATH}.d)
    add_custom_command(
        OUTPUT ${NL_MODEL_C_PATH}
        COMMAND ${Python3_EXECUTABLE} -m nlmodel_tuning.gen_nlmodel_c_file ${NL_MODEL_GEN_ARGS} --input ${NL_MODEL_BIN_DIR}/${NL_MODEL_BIN}
        DEPFILE ${NL_MODEL_C_PATH}.d
        COMMENT "Generating NL Model .c files included in the device and host application"
        VERBATIM
    )

    add_to_build_sources(${NL_MODEL_C_DIR}/${NL_MODEL_C})

    # Set equalization filter and include it in the build
    if (EQ_FILTER_BIN STREQUAL "")
        if (EXISTS ${EQ_FILTER_BIN_DIR}/eq_filter_override.bin)
            message("Found EQ filter override!")
            set(EQ_FILTER_BIN eq_filter_override.bin)
        else()
            set(EQ_FILTER_BIN eq_filter_default.bin)
        endif()
    endif()

    string(REGEX REPLACE "[.]bin$" ".c" EQ_FILTER_C ${EQ_FILTER_BIN})
    # Generate equalization filter C file from the .bin file
    unset(EQ_FILTER_GEN_ARGS)
    set(EQ_FILTER_C_PATH ${EQ_FILTER_C_DIR}/${EQ_FILTER_C})
    list(APPEND EQ_FILTER_GEN_ARGS --out-file ${EQ_FILTER_C_PATH} --append-str all --depfile ${EQ_FILTER_C_PATH}.d)
    add_custom_command(
        OUTPUT ${EQ_FILTER_C_PATH}
        COMMAND ${Python3_EXECUTABLE} -m eq_filter_tuning.gen_eq_filter_c_file ${EQ_FILTER_GEN_ARGS} --input ${EQ_FILTER_BIN_DIR}/${EQ_FILTER_BIN}
        DEPFILE ${EQ_FILTER_C_PATH}.d
        COMMENT "Generating equalization filter .c files included in the device and host application"
        VERBATIM
    )

    add_to_build_sources(${EQ_FILTER_C_DIR}/${EQ_FILTER_C})

    # Pass through the build name and info to allow reading from host app
    add_to_build_opts("BLD_MSG=${PROFILE}")
    set (PRODUCT_DEFAULT_SPECIFIER_${PROFILE} ${PRODUCT_DEFAULT_SPECIFIER})

    #*********************************************************
    # Autogenerate files from the cmds .yaml file
    #*********************************************************

    # For each of the control commands YAMLs, generate a corresponding:
    # x_map.h in device,
    # x_defaults.h in device,
    # x.h in common,
    # x.csv in docs
    # In all of these, blob together shf_aec & aec, shf_pp & pp
    file( GLOB YAML_CONTROL_COMMANDS CONFIGURE_DEPENDS ${YAML_COMMANDS_DIR}/*.yaml )

    # Remove shf_ files we know will be there, we'll put them back in later.
    # This is a slightly hacky bodge since we know they'll all be in the same directory.
    set ( YAML_CONTROL_COMMANDS_NO_SHF ${YAML_CONTROL_COMMANDS})
    list( FILTER YAML_CONTROL_COMMANDS_NO_SHF EXCLUDE REGEX shf_aec_cmds\.yaml)
    list( FILTER YAML_CONTROL_COMMANDS_NO_SHF EXCLUDE REGEX shf_pp_cmds\.yaml)

    foreach(CMD_YAML_PATH ${YAML_CONTROL_COMMANDS_NO_SHF})
        cmake_path(GET CMD_YAML_PATH STEM CMD_YAML)

        set(CMD_MAP_OUT ${AUTOGEN_DEVICE}/${CMD_YAML}_map.h)
        set(CMD_DEFAULTS_OUT ${AUTOGEN_DEVICE}/${PRODUCT_DEFAULT_SPECIFIER}/${CMD_YAML}_defaults.h)
        set(CMD_OUT ${AUTOGEN_COMMON}/${CMD_YAML}.h)
        set(CMD_DOC_OUT ${AUTOGEN_DOCS}/${CMD_YAML}.csv)

        # Deal with blobbing the SHF commands in
        string(FIND ${CMD_YAML} "aec_cmds" IS_AEC)
        string(FIND ${CMD_YAML} "pp_cmds" IS_PP)
        if(NOT IS_AEC EQUAL -1)
            string(REPLACE "aec_cmds.yaml" "shf_aec_cmds.yaml" SHF_AEC ${CMD_YAML_PATH})
            list(APPEND CMD_YAML_PATH ${SHF_AEC})
        endif()
        if(NOT IS_PP EQUAL -1)
            string(REPLACE "pp_cmds.yaml" "shf_pp_cmds.yaml" SHF_PP ${CMD_YAML_PATH})
            list(APPEND CMD_YAML_PATH ${SHF_PP})
        endif()

        add_custom_command(
            OUTPUT ${CMD_MAP_OUT}
            COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_MULTI} -i ${CMD_YAML_PATH} -t ${YAML_TEMPLATES_CMD}/cmd_map_impl.h.jinja -o ${CMD_MAP_OUT}
            COMMENT "Generating ${CMD_YAML}_map.h"
            DEPENDS ${CMD_YAML_PATH} ${YAML_TEMPLATES_CMD}/cmd_map_impl.h.jinja
            VERBATIM
        )
        add_custom_command(
            OUTPUT ${CMD_DEFAULTS_OUT}
            COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_DEFAULTS} -i ${CMD_YAML_PATH} -t ${YAML_TEMPLATES_DEFAULTS}/default_values.h.jinja -o ${CMD_DEFAULTS_OUT} -d ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/control_param_values.yaml -p 3800
            COMMENT "Generating ${CMD_YAML}_defaults.h"
            DEPENDS ${CMD_YAML_PATH} ${YAML_TEMPLATES_DEFAULTS}/default_values.h.jinja ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/control_param_values.yaml
            VERBATIM
        )
        add_custom_command(
            OUTPUT ${CMD_OUT}
            COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_MULTI} -i ${CMD_YAML_PATH} -t ${YAML_TEMPLATES_CMD}/cmd_map.h.jinja -o ${CMD_OUT}
            COMMENT "Generating ${CMD_YAML}.h"
            DEPENDS ${CMD_YAML_PATH} ${YAML_TEMPLATES_CMD}/cmd_map.h.jinja
            VERBATIM
        )

        # For the defaults in the documentation always use the values in
        # app_xvf3800/autogeneration/yaml_files/settings_and_defaults/product/
        add_custom_command(
            OUTPUT ${CMD_DOC_OUT}
            COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_DOCS} -i ${CMD_YAML_PATH} -t ${YAML_TEMPLATES_DOC}/doc_cmd_list.csv.jinja -d ${YAML_SETTINGS_DIR}/product/control_param_values.yaml -o ${CMD_DOC_OUT} --remove-internal --remove-hidden
            COMMENT "Generating ${CMD_YAML}.csv"
            DEPENDS ${CMD_YAML_PATH} ${YAML_TEMPLATES_DOC}/doc_cmd_list.csv.jinja ${YAML_SETTINGS_DIR}/product/control_param_values.yaml
            VERBATIM
        )
        list(APPEND YAML_GENERATED_FILES ${CMD_MAP_OUT} ${CMD_DEFAULTS_OUT} ${CMD_OUT} ${CMD_DOC_OUT})
    endforeach()

    # Generate the other 1-to-1 files:
    # gpi_config.h in device,
    # gpo_config.h in device,
    # mic_geometries.h in device,
    # usb_param_values.h in common,
    # res_id_defines.h in common,
    # device_enums.h in common,
    set(GPI_CFG_OUT ${AUTOGEN_DEVICE}/${PRODUCT_DEFAULT_SPECIFIER}/gpi_config.h)
    set(GPO_CFG_OUT ${AUTOGEN_DEVICE}/${PRODUCT_DEFAULT_SPECIFIER}/gpo_config.h)
    set(MIC_GEO_OUT ${AUTOGEN_DEVICE}/${PRODUCT_DEFAULT_SPECIFIER}/mic_geometries.h)
    set(USB_PARAM_OUT ${AUTOGEN_COMMON}/${PRODUCT_DEFAULT_SPECIFIER}/usb_param_values.h)
    set(RES_IDX_OUT ${AUTOGEN_COMMON}/res_id_defines.h)
    set(RES_IDX_OVERRIDE_OUT ${AUTOGEN_COMMON}/res_id_defines_override.h)
    set(DEVICE_ENUM_OUT ${AUTOGEN_COMMON}/device_enums.h)
    set(TRANSPORT_CFG_OUT ${AUTOGEN_COMMON}/transport_config.h)

    add_custom_command(
        OUTPUT ${GPI_CFG_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_GENERIC} -i ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/gpi_config.yaml -t ${YAML_TEMPLATES_DEFAULTS}/gpi_config.h.jinja -o ${GPI_CFG_OUT} -y gpi
        COMMENT "Generating gpi_config.h"
        DEPENDS ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/gpi_config.yaml ${YAML_TEMPLATES_DEFAULTS}/gpi_config.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${GPO_CFG_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_GENERIC} -i ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/gpo_config.yaml -t ${YAML_TEMPLATES_DEFAULTS}/gpo_config.h.jinja -o ${GPO_CFG_OUT} -y gpo
        COMMENT "Generating gpo_config.h"
        DEPENDS ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/gpo_config.yaml ${YAML_TEMPLATES_DEFAULTS}/gpo_config.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${MIC_GEO_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_GENERIC} -i ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/mic_geometries.yaml -t ${YAML_TEMPLATES_DEFAULTS}/mic_geometries.h.jinja -o ${MIC_GEO_OUT} -y mic
        COMMENT "Generating mic_geometries.h"
        DEPENDS ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/mic_geometries.yaml ${YAML_TEMPLATES_DEFAULTS}/mic_geometries.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${USB_PARAM_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_GENERIC} -i ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/usb_param_values.yaml -t ${YAML_TEMPLATES_DEFAULTS}/usb_params.h.jinja -o ${USB_PARAM_OUT} -y usb
        COMMENT "Generating usb_param_values.h"
        DEPENDS ${YAML_SETTINGS_DIR}/${PRODUCT_DEFAULT_SPECIFIER}/usb_param_values.yaml ${YAML_TEMPLATES_DEFAULTS}/usb_params.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${RES_IDX_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_GENERIC} -i ${YAML_SETTINGS_DIR}/resource_indices.yaml -t ${YAML_TEMPLATES_CMD}/res_id_defines.h.jinja -o ${RES_IDX_OUT} -y indices
        COMMENT "Generating res_id_defines.h"
        DEPENDS ${YAML_SETTINGS_DIR}/resource_indices.yaml ${YAML_TEMPLATES_CMD}/res_id_defines.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${RES_IDX_OVERRIDE_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_GENERIC} -i ${YAML_COMMANDS_DIR}/dfu_cmds.yaml -t ${YAML_TEMPLATES_CMD}/res_id_defines_override.h.jinja -o ${RES_IDX_OVERRIDE_OUT} -y indices_override
        COMMENT "Generating res_id_defines_override.h from dfu_cmds.yaml"
        DEPENDS ${YAML_COMMANDS_DIR}/dfu_cmds.yaml ${YAML_TEMPLATES_CMD}/res_id_defines_override.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${DEVICE_ENUM_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_GENERIC} -i ${YAML_SETTINGS_DIR}/device_enums.yaml -t ${YAML_TEMPLATES_ENUM}/device_enums.h.jinja -o ${DEVICE_ENUM_OUT} -y enums
        COMMENT "Generating device_enums.h"
        DEPENDS ${YAML_SETTINGS_DIR}/device_enums.yaml ${YAML_TEMPLATES_ENUM}/device_enums.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${TRANSPORT_CFG_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_GENERIC} -i ${YAML_SETTINGS_DIR}/transport_config.yaml -t ${YAML_TEMPLATES_DEFAULTS}/transport_config.h.jinja -o ${TRANSPORT_CFG_OUT} -y transport
        COMMENT "Generating transport_config.h"
        DEPENDS ${YAML_SETTINGS_DIR}/transport_config.yaml ${YAML_TEMPLATES_DEFAULTS}/transport_config.h.jinja
        VERBATIM
    )
    list(APPEND YAML_GENERATED_FILES ${GPI_CFG_OUT} ${GPO_CFG_OUT} ${MIC_GEO_OUT} ${USB_PARAM_OUT} ${RES_IDX_OUT} ${DEVICE_ENUM_OUT} ${TRANSPORT_CFG_OUT} ${RES_IDX_OVERRIDE_OUT})

    #message("${YAML_GENERATED_FILES}")

    # Generate the host files:
    # host_cmd_map.h
    # range_check.h
    # range_map.h
    # print_enum_functions.h - enum consumer
    # super_print_arg.h - enum consumer
    # enum_str_map.h

    set(HOST_CMD_OUT ${AUTOGEN_HOST}/host_cmd_map.h)
    set(RANGE_CHECK_OUT ${AUTOGEN_HOST}/range_check.h)
    set(RANGE_MAP_OUT ${AUTOGEN_HOST}/range_map.h)
    set(PRINT_ENUM_FUNC_OUT ${AUTOGEN_HOST}/print_enum_functions.h)
    set(SUPER_PRINT_ARG_OUT ${AUTOGEN_HOST}/super_print_arg.h)
    set(ENUM_STR_MAP_OUT ${AUTOGEN_HOST}/enum_str_map.h)

    add_custom_command(
        OUTPUT ${HOST_CMD_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_MULTI} -i ${YAML_CONTROL_COMMANDS} -t ${YAML_TEMPLATES_CMD}/host_cmd_map_impl.h.jinja -o ${HOST_CMD_OUT} --remove-internal
        COMMENT "Generating host_cmd_map.h"
        DEPENDS ${YAML_CONTROL_COMMANDS} ${YAML_TEMPLATES_CMD}/host_cmd_map_impl.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${RANGE_CHECK_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_MULTI} -i ${YAML_CONTROL_COMMANDS} -t ${YAML_TEMPLATES_CMD}/host_range_check_impl.h.jinja -o ${RANGE_CHECK_OUT} --remove-internal
        COMMENT "Generating range_check.h"
        DEPENDS ${YAML_CONTROL_COMMANDS} ${YAML_TEMPLATES_CMD}/host_range_check_impl.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${RANGE_MAP_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_MULTI} -i ${YAML_CONTROL_COMMANDS} -t ${YAML_TEMPLATES_CMD}/host_range_map_impl.h.jinja -o ${RANGE_MAP_OUT} --remove-internal
        COMMENT "Generating range_map.h"
        DEPENDS ${YAML_CONTROL_COMMANDS} ${YAML_TEMPLATES_CMD}/host_range_map_impl.h.jinja
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${PRINT_ENUM_FUNC_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_ENUM} -i ${YAML_CONTROL_COMMANDS} -t ${YAML_TEMPLATES_ENUM}/print_enum_functions.h.jinja -o ${PRINT_ENUM_FUNC_OUT} --remove-internal -e ${YAML_SETTINGS_DIR}/device_enums.yaml
        COMMENT "Generating print_enum_functions.h"
        DEPENDS ${YAML_CONTROL_COMMANDS} ${YAML_TEMPLATES_ENUM}/print_enum_functions.h.jinja ${YAML_SETTINGS_DIR}/device_enums.yaml
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${SUPER_PRINT_ARG_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_ENUM} -i ${YAML_CONTROL_COMMANDS} -t ${YAML_TEMPLATES_ENUM}/super_print_arg.h.jinja -o ${SUPER_PRINT_ARG_OUT} --remove-internal -e ${YAML_SETTINGS_DIR}/device_enums.yaml
        COMMENT "Generating super_print_arg.h"
        DEPENDS ${YAML_CONTROL_COMMANDS} ${YAML_TEMPLATES_ENUM}/super_print_arg.h.jinja ${YAML_SETTINGS_DIR}/device_enums.yaml
        VERBATIM
    )
    add_custom_command(
        OUTPUT ${ENUM_STR_MAP_OUT}
        COMMAND ${Python3_EXECUTABLE} -m ${YAML_PROC_GENERIC} -i ${YAML_SETTINGS_DIR}/device_enums.yaml -t ${YAML_TEMPLATES_ENUM}/enum_str_map.h.jinja -o ${ENUM_STR_MAP_OUT} -y enums
        COMMENT "Generating enum_str_map.h"
        DEPENDS ${YAML_SETTINGS_DIR}/device_enums.yaml ${YAML_TEMPLATES_ENUM}/enum_str_map.h.jinja
        VERBATIM
    )

    list(APPEND YAML_GENERATED_FILES ${HOST_CMD_OUT} ${RANGE_CHECK_OUT} ${RANGE_MAP_OUT} ${PRINT_ENUM_FUNC_OUT} ${SUPER_PRINT_ARG_OUT} ${ENUM_STR_MAP_OUT})
    if(NOT TARGET yaml_generation_${PRODUCT_DEFAULT_SPECIFIER})
        add_custom_target(yaml_generation_${PRODUCT_DEFAULT_SPECIFIER}
            DEPENDS ${YAML_GENERATED_FILES})
    endif()
    # Create includes list for each build profile
    set(APP_INCLUDES_${PROFILE} ${APP_INCLUDES})
    # Add files with default values
    list(APPEND APP_INCLUDES_${PROFILE} ${AUTOGEN_DIR}/common ${AUTOGEN_DIR}/device ${AUTOGEN_DIR}/device/${PRODUCT_DEFAULT_SPECIFIER} ${AUTOGEN_DIR}/common/${PRODUCT_DEFAULT_SPECIFIER})

endforeach()

foreach(BUILD_PROFILE ${BUILD_PROFILES})

    set(APP_COMPILE_DEFINITIONS ${APP_COMPILE_DEFINITIONS_COMMON})
    list(APPEND APP_COMPILE_DEFINITIONS ${BUILD_OPTS_${BUILD_PROFILE}})
    set(APP_SOURCES ${APP_SOURCES_COMMON})
    list(APPEND APP_SOURCES ${BUILD_SOURCES_${BUILD_PROFILE}})
    set(APP_LINK_LIBRARIES ${APP_COMMON_LINK_LIBRARIES})
    list(APPEND APP_LINK_LIBRARIES ${BUILD_LIBS_${BUILD_PROFILE}})

    set(TARGET_SUFFIX "${BUILD_PROFILE}")

    #**********************
    # Tile Targets
    #**********************
    set(LIB_NAME "lib_application_xvf3800_${TARGET_SUFFIX}")
    add_library(${LIB_NAME} INTERFACE EXCLUDE_FROM_ALL)

    add_dependencies(${LIB_NAME} yaml_generation_${PRODUCT_DEFAULT_SPECIFIER_${BUILD_PROFILE}})

    target_sources(
        ${LIB_NAME}
        INTERFACE
        ${APP_SOURCES}
    )
    target_include_directories(
        ${LIB_NAME}
        INTERFACE
        ${APP_INCLUDES_${BUILD_PROFILE}}
    )

    target_compile_definitions(${LIB_NAME} INTERFACE ${APP_COMPILE_DEFINITIONS})
    target_compile_options(${LIB_NAME} INTERFACE ${APP_COMPILER_FLAGS})
    target_link_libraries(${LIB_NAME} INTERFACE ${APP_LINK_LIBRARIES})
    target_link_options(${LIB_NAME} INTERFACE ${APP_LINK_OPTIONS})

    foreach(TILE 0 1)
        set(TARGET_NAME "tile${TILE}_application_xvf3800_${TARGET_SUFFIX}")
        set(TILE_LIB "lib_tile${TILE}_application_xvf3800_${TARGET_SUFFIX}")
        add_executable(${TARGET_NAME} EXCLUDE_FROM_ALL src/main_tile${TILE}.c)
        add_library(${TILE_LIB} INTERFACE)

        target_compile_definitions(${TILE_LIB} INTERFACE THIS_XCORE_TILE=${TILE})
        target_link_libraries(${TILE_LIB} INTERFACE ${LIB_NAME})
        # Link xshf::xshf library here, so that the app uses lib_xcore_math from fwk_xvf::xvf
        target_link_libraries(${TILE_LIB} INTERFACE xshf::xshf)
        if(TILE EQUAL 1)
            target_link_libraries(${TILE_LIB} INTERFACE fwk_xvf::ep_proxy_remote)
        else()
            target_link_libraries(${TILE_LIB} INTERFACE fwk_xvf::ep_proxy_local)
        endif()

        # Add --map option to store memory map for specific tile
        target_link_options(${TILE_LIB} INTERFACE ${APP_LINK_OPTIONS} -Wm,--map,memory_tile${TILE}.ma)

        target_link_libraries(${TARGET_NAME} PUBLIC ${TILE_LIB})

        unset(TARGET_NAME)
        unset(TILE_LIB)
    endforeach()
    unset(LIB_NAME)

    #**********************
    # Merge binaries
    #**********************

    merge_binaries(
        "application_xvf3800_${TARGET_SUFFIX}"
        "tile0_application_xvf3800_${TARGET_SUFFIX}"
        "tile1_application_xvf3800_${TARGET_SUFFIX}"
        1)
    add_dependencies(all_ci "application_xvf3800_${TARGET_SUFFIX}")

    # Copy output to a handy location
    install(FILES "${CMAKE_CURRENT_BINARY_DIR}/application_xvf3800_${TARGET_SUFFIX}.xe" DESTINATION ${CMAKE_INSTALL_PREFIX}/../release-bin)

    # Copy output to convenient place as a build step.
    file(REAL_PATH ${CMAKE_BINARY_DIR}/../application_xvf3800_${TARGET_SUFFIX}.xe TARGET_COPY_PATH)
    file(RELATIVE_PATH TARGET_PRINT_PATH ${CMAKE_SOURCE_DIR} ${TARGET_COPY_PATH})
    add_custom_command(TARGET application_xvf3800_${TARGET_SUFFIX}
        POST_BUILD
        BYPRODUCTS ${TARGET_COPY_PATH}
        COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_BINARY_DIR}/application_xvf3800_${TARGET_SUFFIX}.xe ${TARGET_COPY_PATH}
        # print a message to make it clear that this binary has been built
        COMMAND ${CMAKE_COMMAND} -E cmake_echo_color --green --bold "Finished building ${TARGET_PRINT_PATH}")

    #**********************
    # Create run and debug targets
    #**********************
    add_custom_target("run_application_xvf3800_${TARGET_SUFFIX}"
      COMMAND "xrun --xscope application_xvf3800_${TARGET_SUFFIX}.xe"
      DEPENDS ${_EXECUTABLE_TARGET_NAME}
      COMMENT
        "Run application"
      VERBATIM
    )

    create_debug_target("application_xvf3800_${TARGET_SUFFIX}")
    create_flash_app_target("application_xvf3800_${TARGET_SUFFIX}")

endforeach()
