// Copyright 2022-2024 XMOS LIMITED.
// This Software is subject to the terms of the XCORE VocalFusion Licence.


#ifndef PLATFORM_CONF_H_
#define PLATFORM_CONF_H_

/*
 * Board support package for XK-VOICE-SQ66 EVK
 */

#if __has_include("app_conf.h")
#include "app_conf.h"
#endif /* __has_include("app_conf.h") */

/*****************************************/
/* Intertile Communication Configuration */
/*****************************************/

/*****************************************/
/*  I/O and interrupt cores for Tile 0   */
/*****************************************/

#define USB_EP0_TILE_NO 0

#define I2C_TILE_NO     0
#define FLASH_TILE_NO   0

// Assuming we only ever have I2C or SPI, not both.
#define appconfI2C_IO_CORE                      1 /* Must be kept off core 0 with the RTOS tick ISR */
#define appconfSPI_IO_CORE                     appconfI2C_IO_CORE /* Must be kept off core 0 with the RTOS tick ISR. Must be kept off appconfI2C_IO_CORE since i2c hil task is non preemptable */

#define appconfI2C_ISR_CORE                     2 /* Must be kept off core 0 with the RTOS tick ISR. Must be kept off appconfI2C_IO_CORE since i2c hil task is non preemptable */
#define appconfSPI_ISR_CORE                     appconfI2C_ISR_CORE /* Must be kept off core 0 with the RTOS tick ISR. Must be kept off appconfI2C_IO_CORE since i2c hil task is non preemptable */

#if (appconfUSB_ENABLED == 0)
#define GPO_PWM_ISR_CORE                        appconfI2C_ISR_CORE
#else
#define GPO_PWM_ISR_CORE                        0 // Always run GPO interrupt on core0 to keep core1, if present for RTOS, free for the USB interrupts
#endif

#if (appconfNUM_FREE_RTOS_CORES > 1)
#define EP_PROXY_ISR_CORE 1
#define EP_PROXY_HID_ISR_CORE 0
#else
#define EP_PROXY_ISR_CORE 0     // Highly unlikely this will work if we put the EP0 interrupts on core 0
#define EP_PROXY_HID_ISR_CORE 0 // We see deadlocks with both of these ISRs on the same core, so this is a highly inadvisable configuration.
#endif

#define appconfXUD_IO_CORE                      2
#define appconfUSB_SOF_INTERRUPT_CORE           -1 // We don't want SOF interrupt in RTOS
#define appconfUSB_INTERRUPT_CORE               1
#define appconfUSB_BUFFER_CORE                  3

#include <transport_config.h> // Autogenerated, gives I2C_ADDRESS and SPI_MODE

#define I2C_SLAVE_ADDR       I2C_ADDRESS

#define SPI_TILE_NO 0

#if SPI_MODE == 0
#define SPI_SLAVE_CPOL 0
#define SPI_SLAVE_CPHA 0
#elif SPI_MODE == 1
#define SPI_SLAVE_CPOL 0
#define SPI_SLAVE_CPHA 1
#elif SPI_MODE == 2
#define SPI_SLAVE_CPOL 1
#define SPI_SLAVE_CPHA 0
#elif SPI_MODE == 3
#define SPI_SLAVE_CPOL 1
#define SPI_SLAVE_CPHA 1
#else
#error "SPI_MODE set to invalid value - must be 0,1,2, or 3"
#endif

#ifndef appconfQSPI_FLASH_TASK_PRIORITY
#define appconfQSPI_FLASH_TASK_PRIORITY ( configMAX_PRIORITIES - 1 )
#endif /* appconfQSPI_FLASH_TASK_PRIORITY */

#ifndef appconfI2C_MASTER_RPC_PORT
#define appconfI2C_MASTER_RPC_PORT 10
#endif /* appconfI2C_MASTER_RPC_PORT */

#ifndef appconfI2C_MASTER_RPC_PRIORITY
#define appconfI2C_MASTER_RPC_PRIORITY (configMAX_PRIORITIES/2)
#endif /* appconfI2C_MASTER_RPC_PRIORITY */

#define GPI_PORT_TILE_NO     1

/*****************************************/
/*  I/O and interrupt cores for Tile 1   */
/*****************************************/

/*****************************************/
/*  I/O Task Priorities                  */
/*****************************************/
/*****************************************/
/*  DFU Settings                         */
/*****************************************/

// Tools 15.2.x don't require a specific QSPI_SPEC info
#ifndef BOARD_QSPI_SPEC
#define BOARD_QSPI_SPEC     FL_QUADDEVICE_DEFAULT
#endif /* BOARD_QSPI_SPEC */

#endif /* PLATFORM_CONF_H_ */
