"""Derive the CUDA successor launch package from the frozen CPU campaign coverage.

This command maps each selected CPU scenario to the uniquely matching CUDA
scenario generated by the public Stage 2 contracts. It never edits either
scenario catalog or a materialized campaign in place.
"""

from __future__ import annotations

import argparse
from copy import deepcopy
from datetime import datetime
import json
from pathlib import Path
import sys
import tempfile
from typing import Mapping

import yaml


TOOL_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = TOOL_ROOT.parents[1]
if str(TOOL_ROOT) not in sys.path:
    sys.path.insert(0, str(TOOL_ROOT))

from app.artifact_contracts.atomic import file_sha256  # noqa: E402
from app.artifact_contracts.registry import (  # noqa: E402
    LATEST_ARTIFACT_REGISTRY_VERSION,
    ArtifactRegistry,
)
from app.campaign_exchange import create_worker_assignment, current_git_commit  # noqa: E402
from app.campaign_exchange.common import atomic_write_yaml  # noqa: E402
from app.campaign_executor.planner import plan_campaign  # noqa: E402
from app.utils.json_utils import read_jsonl  # noqa: E402


class GPULaunchPackageError(RuntimeError):
    """Raised when CPU coverage cannot map one-to-one to CUDA scenarios."""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--reference-package",
        type=Path,
        default=TOOL_ROOT
        / "configs"
        / "automated_evaluation"
        / "launch_package.v1.yaml",
    )
    parser.add_argument(
        "--gpu-catalog",
        type=Path,
        default=TOOL_ROOT
        / "benchmarks"
        / "v1"
        / "resolved_scenarios_cuda_float32.jsonl",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=TOOL_ROOT
        / "configs"
        / "automated_evaluation"
        / "launch_package.gpu.v1.yaml",
    )
    parser.add_argument(
        "--campaign-id", default="campaign_06_massive_release_cuda"
    )
    parser.add_argument("--environment-profile", default="core-cuda")
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--dtype", default="float32")
    parser.add_argument("--estimated-rtf", type=float)
    parser.add_argument("--estimated-rtf-low", type=float)
    parser.add_argument("--estimated-rtf-high", type=float)
    return parser


def build_package(
    *,
    reference_package_path: Path,
    gpu_catalog_path: Path,
    output_path: Path,
    campaign_id: str,
    environment_profile: str,
    device: str,
    dtype: str,
    estimated_rtf: float | None = None,
    estimated_rtf_low: float | None = None,
    estimated_rtf_high: float | None = None,
) -> dict[str, object]:
    reference = _read_mapping(reference_package_path)
    cpu = _mapping(reference.get("massive_campaign"), "reference massive campaign")
    cpu_catalog_path = TOOL_ROOT / str(
        _mapping(cpu.get("source_catalog"), "reference source catalog")["path"]
    )
    cpu_scenarios = {
        str(row["scenario_id"]): row for row in read_jsonl(cpu_catalog_path)
    }
    gpu_rows = list(read_jsonl(gpu_catalog_path.resolve()))
    gpu_by_key: dict[str, list[Mapping[str, object]]] = {}
    for scenario in gpu_rows:
        runtime = _mapping(scenario.get("runtime"), "GPU scenario runtime")
        if runtime.get("device") != device or runtime.get("dtype") != dtype:
            continue
        gpu_by_key.setdefault(_coverage_key(scenario), []).append(scenario)

    cpu_ids = [str(value) for value in cpu["scenario_ids"]]
    mapped: dict[str, str] = {}
    for cpu_id in cpu_ids:
        cpu_scenario = cpu_scenarios.get(cpu_id)
        if cpu_scenario is None:
            raise GPULaunchPackageError(f"CPU scenario is absent from catalog: {cpu_id}")
        candidates = gpu_by_key.get(_coverage_key(cpu_scenario), [])
        if len(candidates) != 1:
            raise GPULaunchPackageError(
                f"CPU scenario {cpu_id} maps to {len(candidates)} CUDA scenarios"
            )
        candidate = candidates[0]
        if _mapping(candidate["dataset_slice"], "GPU slice").get("row_count") != _mapping(
            cpu_scenario["dataset_slice"], "CPU slice"
        ).get("row_count"):
            raise GPULaunchPackageError(f"row count changed while mapping {cpu_id}")
        mapped[cpu_id] = str(candidate["scenario_id"])

    selected_gpu_ids = sorted(mapped.values())
    if len(set(selected_gpu_ids)) != len(cpu_ids):
        raise GPULaunchPackageError("CUDA scenario mapping is not one-to-one")

    created_at = str(cpu["created_at_utc"])
    expected_commit = current_git_commit(REPOSITORY_ROOT)
    with tempfile.TemporaryDirectory(prefix="gpu-launch-package-") as temporary:
        campaign_root = plan_campaign(
            scenario_catalog=gpu_catalog_path.resolve(),
            automated_runs_root=Path(temporary),
            campaign_id=campaign_id,
            scenario_ids=selected_gpu_ids,
            default_max_retries=int(cpu["default_max_retries"]),
            created_at=_timestamp(created_at),
            registry=ArtifactRegistry.load_version(LATEST_ARTIFACT_REGISTRY_VERSION),
        ).campaign_root
        campaign_manifest_sha256 = file_sha256(
            campaign_root / "campaign_manifest.json"
        )
        workers: dict[str, object] = {}
        cpu_workers = _mapping(cpu.get("workers"), "reference workers")
        for worker_name in ("machine_a", "machine_b"):
            source_worker = _mapping(cpu_workers.get(worker_name), worker_name)
            scenario_ids = sorted(
                mapped[str(value)] for value in source_worker["scenario_ids"]
            )
            assignment_path = campaign_root / "worker_assignments" / f"{worker_name}.yaml"
            assignment = create_worker_assignment(
                campaign_root,
                worker_id=str(source_worker["worker_id"]),
                expected_git_commit=expected_commit,
                expected_environment_profile=environment_profile,
                scenario_ids=scenario_ids,
                notes=(
                    "Coverage-preserving CUDA successor of the frozen CPU assignment; "
                    "one GPU-heavy scenario at a time."
                ),
                created_at=_timestamp(str(source_worker["created_at_utc"])),
                output_path=assignment_path,
            )
            workers[worker_name] = {
                "worker_id": source_worker["worker_id"],
                "assignment_path": f"worker_assignments/{worker_name}.yaml",
                "assignment_id": assignment["assignment_id"],
                "assignment_sha256": assignment["assignment_sha256"],
                "created_at_utc": source_worker["created_at_utc"],
                "scenario_count": len(scenario_ids),
                "item_execution_count": source_worker["item_execution_count"],
                "audio_hours": source_worker["audio_hours"],
                "estimated_runtime_hours": _runtime_estimate(
                    float(source_worker["audio_hours"]),
                    len(scenario_ids),
                    point=estimated_rtf,
                    low=estimated_rtf_low,
                    high=estimated_rtf_high,
                    fallback=_mapping(
                        source_worker.get("estimated_runtime_hours"),
                        "reference runtime estimate",
                    ),
                ),
                "estimated_artifact_bytes": source_worker["estimated_artifact_bytes"],
                "notes": (
                    "Coverage-preserving mapping from the frozen CPU assignment. "
                    "Machine-specific CUDA readiness must be proven independently."
                ),
                "scenario_ids": scenario_ids,
            }

    massive = deepcopy(dict(cpu))
    massive.update(
        {
            "campaign_id": campaign_id,
            "campaign_root": f"automated_runs/{campaign_id}",
            "campaign_manifest_sha256": campaign_manifest_sha256,
            "source_catalog": {
                "path": gpu_catalog_path.resolve().relative_to(TOOL_ROOT).as_posix(),
                "sha256": file_sha256(gpu_catalog_path.resolve()),
            },
            "environment_profile": environment_profile,
            "device": device,
            "dtype": dtype,
            "scenario_ids": selected_gpu_ids,
            "workers": workers,
        }
    )
    package: dict[str, object] = {
        "schema_version": "launch-package.v1",
        "readiness_state": "NOT_READY_TO_LAUNCH",
        "generated_at_utc": datetime.now().astimezone().isoformat(),
        "repository": {
            "remote": _mapping(reference.get("repository"), "repository").get("remote"),
            "branch": _mapping(reference.get("repository"), "repository").get("branch"),
            "commit_binding_policy": "post_commit_runtime_head",
            "expected_commit": expected_commit,
            "freeze_status": "gpu_candidate_evidence_commit_before_final_binding",
        },
        "reference_cpu_campaign": {
            "campaign_id": cpu["campaign_id"],
            "campaign_manifest_sha256": cpu["campaign_manifest_sha256"],
            "source_catalog_sha256": _mapping(
                cpu["source_catalog"], "reference source catalog"
            )["sha256"],
            "device": cpu["device"],
            "dtype": cpu["dtype"],
            "environment_profile": cpu["environment_profile"],
            "preserved": True,
        },
        "campaigns": [
            {
                "id": campaign_id,
                "scenario_count": len(selected_gpu_ids),
                "manifest_sha256": campaign_manifest_sha256,
                "execution_status": "gpu_candidate_not_launched",
            }
        ],
        "massive_campaign": massive,
        "blockers": [
            "Machine B has not completed CUDA installation, machine profiling, or full-assignment preflight.",
            "Component canary, small, and standard scientific gates remain required before massive execution.",
            "Bedroom RIR remains unresolved and excluded without substitution.",
        ],
    }
    atomic_write_yaml(output_path.resolve(), package)
    return package


def _coverage_key(scenario: Mapping[str, object]) -> str:
    fields = (
        "benchmark_manifest",
        "panel",
        "tier",
        "dataset_slice",
        "condition",
        "seed",
        "repetition",
        "timeout_policy",
        "resource_policy",
        "scoring_policy_version",
        "failure_policy",
    )
    payload = {field: scenario[field] for field in fields}
    manifest = _mapping(payload["benchmark_manifest"], "benchmark manifest")
    payload["benchmark_manifest"] = {
        key: manifest[key] for key in ("schema_version", "manifest_id", "sha256")
    }
    return json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _runtime_estimate(
    audio_hours: float,
    scenario_count: int,
    *,
    point: float | None,
    low: float | None,
    high: float | None,
    fallback: Mapping[str, object],
) -> dict[str, float]:
    if point is None or low is None or high is None:
        return {key: float(fallback[key]) for key in ("low", "point", "high")}
    initialization_hours = scenario_count * 20.0 / 3600.0
    return {
        "low": round(audio_hours * low + initialization_hours, 5),
        "point": round(audio_hours * point + initialization_hours, 5),
        "high": round(audio_hours * high + initialization_hours, 5),
    }


def _read_mapping(path: Path) -> Mapping[str, object]:
    value = yaml.safe_load(path.resolve().read_text(encoding="utf-8"))
    return _mapping(value, str(path))


def _mapping(value: object, label: str) -> Mapping[str, object]:
    if not isinstance(value, Mapping):
        raise GPULaunchPackageError(f"{label} must be an object")
    return value


def _timestamp(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    package = build_package(
        reference_package_path=args.reference_package,
        gpu_catalog_path=args.gpu_catalog,
        output_path=args.output,
        campaign_id=args.campaign_id,
        environment_profile=args.environment_profile,
        device=args.device,
        dtype=args.dtype,
        estimated_rtf=args.estimated_rtf,
        estimated_rtf_low=args.estimated_rtf_low,
        estimated_rtf_high=args.estimated_rtf_high,
    )
    massive = _mapping(package["massive_campaign"], "massive campaign")
    print(
        json.dumps(
            {
                "campaign_id": massive["campaign_id"],
                "campaign_manifest_sha256": massive["campaign_manifest_sha256"],
                "scenario_catalog_sha256": _mapping(
                    massive["source_catalog"], "source catalog"
                )["sha256"],
                "scenario_count": massive["scenario_count"],
                "device": massive["device"],
                "dtype": massive["dtype"],
                "workers": massive["workers"],
                "output": str(args.output.resolve()),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
