const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('measurement_app/static/app.js', 'utf8');
const start = source.indexOf('  function recoveredPlaybackIndex(');
const end = source.indexOf('\n  }', start) + 4;
assert(start >= 0 && end > start);
const context = {hostApiName: d => d?.hostapi_name ?? null};
vm.createContext(context);
vm.runInContext(source.slice(start, end), context);
const select = context.recoveredPlaybackIndex;
const output = (index, api='Windows WASAPI') => ({index, name:'Speakers (Realtek)',hostapi_name:api,max_output_channels:2,approved_for_playback:true});
assert.equal(select([output(14)], '14', 'Speakers (Realtek)', 'Windows WASAPI'), '14');
assert.equal(select([output(19),output(14,'MME')], '14', 'Speakers (Realtek)', 'Windows WASAPI'), '19');
assert.equal(select([output(19),output(20)], '14', 'Speakers (Realtek)', 'Windows WASAPI'), null);
assert.equal(select([output(19)], '14', 'Speakers (Realtek)', null), null);
assert.equal(select([], '14', 'Speakers (Realtek)', 'Windows WASAPI'), null);
assert.equal(select([{...output(19),approved_for_playback:false}], '14', 'Speakers (Realtek)', 'Windows WASAPI'), null);
console.log('PASS: recovered endpoint identity, index remap, host API match, ambiguity and missing-device rejection.');
