"""Download and pin ARM64 wheels without installing them; see README.md."""
from __future__ import annotations
import argparse
import hashlib
import json
import subprocess
import sys
import urllib.request
import zipfile
from datetime import datetime, timezone
from email.parser import BytesParser
from pathlib import Path


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output', type=Path, required=True)
    a = p.parse_args()
    a.output.mkdir(parents=True, exist_ok=True)
    base = Path(__file__).resolve().parent
    subprocess.run([sys.executable, '-m', 'pip', 'download', '--only-binary=:all:',
        '--python-version', '311', '--implementation', 'cp', '--abi', 'cp311', '--abi', 'abi3',
        '--platform', 'manylinux_2_28_aarch64', '--platform', 'manylinux_2_27_aarch64',
        '--platform', 'manylinux2014_aarch64', '--platform', 'manylinux_2_17_aarch64',
        '--dest', str(a.output), '-r', str(base / 'requirements-arm64.in')], check=True)
    rows = []
    for path in sorted(a.output.glob('*.whl')):
        with zipfile.ZipFile(path) as z:
            meta = BytesParser().parsebytes(z.read(next(n for n in z.namelist() if n.endswith('.dist-info/METADATA'))))
            license_dir = base / 'licenses' / meta['Name'].replace('-', '_')
            license_dir.mkdir(parents=True, exist_ok=True)
            for i, name in enumerate(n for n in z.namelist() if '.dist-info/' in n and any(x in n.lower() for x in ['license', 'copying', 'notice']) and not n.endswith('/')):
                # Preserve licence text from the publisher's wheel, not paraphrases.
                (license_dir / f'{i:02d}_{Path(name).name}.txt').write_bytes(z.read(name))
        name, version = meta['Name'], meta['Version']
        url = f'https://pypi.org/pypi/{name}/{version}/json'
        with urllib.request.urlopen(url, timeout=30) as response:
            published = json.load(response)
        entry = next(x for x in published['urls'] if x['filename'] == path.name)
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != entry['digests']['sha256']:
            raise RuntimeError(f'Published checksum mismatch: {path.name}')
        rows.append(dict(name=name, version=version, filename=path.name, sha256=digest,
            bytes=path.stat().st_size, source=url, download_url=entry['url'],
            license_expression=meta.get('License-Expression'), license=meta.get('License', '')[:2000]))
    receipt = dict(schema='just-peachy.arm64-wheels.v1', checked_utc=datetime.now(timezone.utc).isoformat(),
        target=dict(os='Raspberry Pi OS 64-bit Bookworm', arch='aarch64', python='3.11', glibc_min='2.36'),
        status='ARM64_ARTIFACT_PREPARED', native_execution='CM5_HARDWARE_NOT_TESTED', files=rows,
        system_libraries=['python3.11-venv', 'python3-tk', 'libportaudio2', 'libsndfile1', 'libusb-1.0-0', 'libgomp1'],
        xmos='Matched ARM64 USB host and command-map libraries still require a native source build and hardware proof.')
    (base / 'evidence' / 'ARM64_WHEELS.json').write_text(json.dumps(receipt, indent=2) + '\n', encoding='utf-8')
    lock = '# Downloaded ARM64 CPython 3.11 wheel hashes; generated by prepare_arm64.py.\n'
    lock += '\n'.join(f"{r['name']}=={r['version']} --hash=sha256:{r['sha256']}" for r in rows) + '\n'
    (base / 'requirements-arm64.lock').write_text(lock, encoding='utf-8')
    print(json.dumps(dict(status=receipt['status'], wheels=len(rows), bytes=sum(r['bytes'] for r in rows), output=str(a.output))))


if __name__ == '__main__':
    main()
