"""Backend-neutral runtime interfaces.

The protocols deliberately exchange small runtime value objects and JSON-safe
records.  Model-specific objects stay behind their isolated worker boundary.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable, Mapping, Protocol, Sequence, runtime_checkable

from .models import (
    AnonymousClusterUpdate,
    EmbeddingResult,
    EmbeddingWindow,
    NormalizedAudioFrame,
    RawAudioFrame,
    SpeechRegionUpdate,
    WorkerStatus,
)


@runtime_checkable
class AudioSource(Protocol):
    def start(self) -> None: ...
    def read(self, timeout_sec: float | None = None) -> RawAudioFrame | None: ...
    def stop(self) -> None: ...
    def reset(self) -> None: ...
    def status(self) -> Mapping[str, object]: ...


@runtime_checkable
class AudioNormalizer(Protocol):
    def normalize(self, frame: RawAudioFrame) -> NormalizedAudioFrame: ...
    def reset(self) -> None: ...


@runtime_checkable
class StreamingASRAdapter(Protocol):
    backend_id: str

    def start(self, session_id: str) -> None: ...
    def accept_audio(
        self, frame: NormalizedAudioFrame
    ) -> Sequence[Mapping[str, object]]: ...
    def finalize(self, reason: str) -> Sequence[Mapping[str, object]]: ...
    def reset(self, reason: str) -> Sequence[Mapping[str, object]]: ...
    def status(self) -> Mapping[str, object]: ...
    def close(self) -> None: ...


@runtime_checkable
class StreamingSegmenter(Protocol):
    backend_id: str
    algorithmic_lookahead_sec: float

    def start(self, session_id: str) -> None: ...
    def accept_audio(
        self, frame: NormalizedAudioFrame
    ) -> Sequence[SpeechRegionUpdate]: ...
    def finalize(self) -> Sequence[SpeechRegionUpdate]: ...
    def reset(self) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class DiarizationEmbeddingAdapter(Protocol):
    backend_id: str

    def embed(self, window: EmbeddingWindow) -> EmbeddingResult: ...
    def status(self) -> Mapping[str, object]: ...
    def close(self) -> None: ...


@runtime_checkable
class OnlineClusterManager(Protocol):
    def update(
        self, embedding: EmbeddingResult, window: EmbeddingWindow
    ) -> AnonymousClusterUpdate: ...
    def finalize(self) -> Sequence[AnonymousClusterUpdate]: ...
    def reset(self) -> None: ...


@runtime_checkable
class IdentityEmbeddingAdapter(Protocol):
    backend_id: str

    def embed(self, window: EmbeddingWindow) -> EmbeddingResult: ...
    def status(self) -> Mapping[str, object]: ...
    def close(self) -> None: ...


@runtime_checkable
class EnrollmentStore(Protocol):
    def load_profiles(self, backend_id: str) -> Sequence[Any]: ...
    def get_profile(self, profile_id: str) -> Any: ...
    def save_profile(self, profile: Any) -> Path: ...
    def status(self) -> Mapping[str, object]: ...


@runtime_checkable
class OpenSetIdentityPolicy(Protocol):
    policy_id: str

    def evaluate(self, *args: Any, **kwargs: Any) -> Any: ...
    def threshold_contract(self, gallery_size: int) -> Mapping[str, object]: ...


@runtime_checkable
class SessionIdentityManager(Protocol):
    def update(self, *args: Any, **kwargs: Any) -> Any: ...
    def label_for(self, anonymous_speaker_id: str) -> str: ...
    def reset(self) -> None: ...
    def clear_anonymous_memory(self) -> None: ...
    def session_state(self) -> Mapping[str, object]: ...


@runtime_checkable
class TranscriptSpeakerAligner(Protocol):
    def ingest_asr(
        self, event: Mapping[str, object]
    ) -> Mapping[str, object] | None: ...
    def add_anonymous_region(
        self, *args: Any, **kwargs: Any
    ) -> Mapping[str, object] | None: ...
    def revise_identity(
        self, *args: Any, **kwargs: Any
    ) -> Mapping[str, object] | None: ...
    def snapshot(self) -> Mapping[str, object]: ...
    def seal_existing_spans(self) -> Sequence[str]: ...
    def reset(self) -> None: ...


@runtime_checkable
class PipelineCoordinator(Protocol):
    def run(self) -> Mapping[str, object]: ...
    def request_stop(self) -> None: ...
    def status(self) -> Mapping[str, object]: ...
    def reset_session(
        self, *, preserve_transcript: bool = True
    ) -> Mapping[str, object]: ...
    def clear_anonymous_memory(
        self, *, preserve_transcript: bool = True
    ) -> Mapping[str, object]: ...


@runtime_checkable
class EventSink(Protocol):
    def emit(self, event: Mapping[str, object]) -> None: ...
    def close(self) -> None: ...
    def events(self) -> Sequence[Mapping[str, object]]: ...


@runtime_checkable
class ResourceMonitor(Protocol):
    def start(self) -> None: ...
    def sample_now(self) -> Mapping[str, object]: ...
    def stop(self) -> None: ...
    def samples(self) -> Iterable[Mapping[str, object]]: ...


@runtime_checkable
class WorkerSupervisor(Protocol):
    def start(self) -> WorkerStatus: ...
    def request(
        self, operation: str, payload: Mapping[str, object] | None = None
    ) -> Mapping[str, object]: ...
    def health(self) -> WorkerStatus: ...
    def restart(self) -> WorkerStatus: ...
    def close(self) -> None: ...
