// Copyright 2022-2023 XMOS LIMITED.
// This Software is subject to the terms of the XCORE VocalFusion Licence.
#include "res_id_defines.h" // Autogenerated

// Tile 0 bare metal resources
// PP
// Tile 0 RTOS resources
// DFU controller.
// Tile 0 servicers
// - PP servicer
#define NUM_RESOURCES_PP_SERVICER (1 + 1) // PP servicer and PP resource
// - DFU servicer which will handle DFU commands
#define NUM_RESOURCES_DFU_SERVICER (1) // DFU servicer
// GPO servicer
#define NUM_RESOURCES_GPO_SERVICER (1) // GPO servicer. This is a servicer that is also an underlying resource of the IO config servicer.
// USB Buffer Servicer
#define NUM_RESOURCES_USB_BUFFER_SERVICER (1)

// Tile 1 bare-metal resources
// AEC, I2S+Customer DSP, Audio Manager + Post SHF DSP + Pre SHF DSP
// Tile 1 RTOS resources
// IO config
// Tile 1 servicers
// - AEC
#define NUM_RESOURCES_AEC_SERVICER (1 + 1) // AEC servicer and AEC resource
// - I2S + AudioManager
#define NUM_RESOURCES_AUDIO_MGR_SERVICER (1 + 1) // AudioMgr servicer and AudioMgr resource
// IO config
#define NUM_RESOURCES_IO_CONFIG_SERVICER (1 + 1) // IO config servicer and GPO servicer which acts like a resource to IO config. IO config talks to the GPO servicer over the internal device_control_gpio_ctx
// Application servicer
#define NUM_RESOURCES_APPLICATION_SERVICER (1)
// PLL Servicer
#define NUM_RESOURCES_PLL_SERVICER (1)

// For accessing servicer arrays.
enum e_servicer_indexes {
    // Tile 0
    PP_SERVICER_INDEX = 0,
#if (DFU_CONTROL > 0) && !appconfUSB_ENABLED
    DFU_SERVICER_INDEX,
#endif
    GPO_SERVICER_INDEX,
    USB_BUFFER_SERVICER_INDEX,
    NUM_TILE_0_SERVICERS,
    // Tile 1
    AEC_SERVICER_INDEX = 0,
    AUDIO_SERVICER_INDEX,
    IO_CONFIG_SERVICER_INDEX,
    APPLICATION_SERVICER_INDEX,
    PLL_SERVICER_INDEX,
#if IO_EXPANDER_ENABLED
    IO_EXPANDER_SERVICER_INDEX,
#endif
    NUM_TILE_1_SERVICERS
};
