// Copyright 2022-2023 XMOS LIMITED.
// This Software is subject to the terms of the XCORE VocalFusion Licence.
#define DEBUG_UNIT SERVICER_INIT
#ifndef DEBUG_PRINT_ENABLE_SERVICER_INIT
    #define DEBUG_PRINT_ENABLE_SERVICER_INIT 0
#endif
#include "debug_print.h"

#include <stdio.h>
#include <platform.h>
#include "platform/platform_conf.h"
#include "device_control_i2c.h"
#include "device_control_spi.h"
#include "servicer.h"
#include "pll_servicer.h"
#include "aec_cmds.h" // Autogenerated file
#include "pp_cmds.h" // Autogenerated file
#include "audio_cmds.h" // Autogenerated file
#include "application_cmds.h" // Autogenerated file
#include "io_config_cmds.h" // Autogenerated
#include "usb_buffer_cmds.h" // Autogenerated
#include "pll_cmds.h" // Autogenerated
#include "dfu_cmds.h" // Autogenerated
#include "control_init.h"
#include "BeClearCommon.h"
#include "shf_wrapper.h"

//-----------------Servicer initialisation functions-----------------------//
/**
 * @brief Initialise packer payload pointers in the pkt_queue to point to valid memory buffers.
 * \param pkt_queue      Pointer to the pkt queue.
 * \param payload_buffer Pointer to the buffer that is used to initialise the payload pointers with
 * \param payload_bytes_per_pkt Size of payload buffer per packet.
 */
static void init_pkt_queue(control_pkt_queue_t *pkt_queue, uint8_t *payload_buffer, size_t payload_bytes_per_pkt)
{
    for(int i=0; i<pkt_queue->depth; i++)
    {
        pkt_queue->pkts[i].payload = &payload_buffer[i*payload_bytes_per_pkt];
        pkt_queue->queue_rd_index = 0;
        pkt_queue->queue_wr_index = 0;
        pkt_queue->pkts[i].save_payload_ptr = NULL;
    }
}

// These initialisation functions set up the servicer data structure which is passed to the servicer task.
#define MAX_AEC_FILTER_SIZE (BECLEAR_MAX_AEC_LENGTH)

// AEC resource
#define MAX_PKT_QUEUE_LEN_AEC (8)
#define MAX_PKT_PAYLOAD_AEC (64)

//Audio Manager resource
#define MAX_PKT_QUEUE_LEN_AUDIO_MGR (3)
#define MAX_PKT_PAYLOAD_AUDIO_MGR (64)

// I2S resource
#define MAX_PKT_QUEUE_LEN_I2S (2)
#define MAX_PKT_PAYLOAD_I2S (64)

void aec_servicer_init(servicer_t *servicer)
{
    #include "aec_cmds_map.h" // Included instead of directly adding code since this file is autogenerated.
    // AEC servicer buffers
    static control_pkt_t control_pkts_aec[MAX_PKT_QUEUE_LEN_AEC];
    static uint8_t total_payload_buf_aec[MAX_PKT_QUEUE_LEN_AEC * MAX_PKT_PAYLOAD_AEC];
    static float aec_filter_buffer[AEC_COEFF_CHUNK_SIZE + MAX_COEFFS_PER_PKT - 1];
    // Servicer resource info
    static control_resource_info_t aec_res_info[NUM_RESOURCES_AEC_SERVICER];

    memset(servicer, 0, sizeof(servicer_t));
    servicer->id = AEC_SERVICER_RESID;
    servicer->start_io = 0; // No IO tasks on tile 1
    servicer->num_resources = NUM_RESOURCES_AEC_SERVICER;

    servicer->res_info = &aec_res_info[0];
    // Servicer resource
    servicer->res_info[0].resource = AEC_SERVICER_RESID;
    // The servicer resource needs to issue commands to the underlying resource
    // so needs visibility of the message queue on which to communicate with the underlying resource
    servicer->res_info[0].control_pkt_queue.depth = 0;
    servicer->res_info[0].control_pkt_queue.pkts = NULL;
    servicer->res_info[0].command_map.num_commands = NUM_AEC_SERVICER_RESID_CMDS;
    servicer->res_info[0].command_map.commands = &aec_servicer_resid_cmd_map[0];
    servicer->res_info[0].special_cmd_handler.special_commands_buffer = NULL;
    servicer->res_info[0].special_cmd_handler.special_cmds_buf_size = 0;

    // AEC resource
    servicer->res_info[1].resource = AEC_RESID;
    servicer->res_info[1].control_pkt_queue.depth = MAX_PKT_QUEUE_LEN_AEC;
    servicer->res_info[1].control_pkt_queue.pkts = &control_pkts_aec[0];
    servicer->res_info[1].command_map.num_commands = NUM_AEC_RESID_CMDS;
    servicer->res_info[1].command_map.commands = &aec_resid_cmd_map[0];
    servicer->res_info[1].special_cmd_handler.special_commands_buffer = (uint8_t*)&aec_filter_buffer[0];
    servicer->res_info[1].special_cmd_handler.special_cmds_buf_size = AEC_COEFF_CHUNK_SIZE; // This would be just the chunk_size and doesn't take the MAX_COEFFS_PER_PKT - 1 extra space into account
    servicer->res_info[1].special_cmd_handler.special_cmds_buf_overflow_size = MAX_COEFFS_PER_PKT - 1;


    // Initialise payload pointers in the pkt_queue
    init_pkt_queue(&servicer->res_info[1].control_pkt_queue, total_payload_buf_aec, MAX_PKT_PAYLOAD_AEC);
}

void audio_servicer_init(servicer_t *servicer)
{
    #include "audio_cmds_map.h" // Included instead of directly adding code since this file is autogenerated.
    // Audio Mgr Servicer buffers
    static control_pkt_t control_pkts_audio_mgr[MAX_PKT_QUEUE_LEN_AUDIO_MGR];
    static uint8_t total_payload_buf_audio_mgr[MAX_PKT_QUEUE_LEN_AUDIO_MGR * MAX_PKT_PAYLOAD_AUDIO_MGR];
    //static uint8_t *audio_mgr_special_commands_buffer = NULL;
    // Servicer resource info
    static control_resource_info_t audio_res_info[NUM_RESOURCES_AUDIO_MGR_SERVICER];

    memset(servicer, 0, sizeof(servicer_t));

    servicer->id = AUDIO_SERVICER_RESID;
    servicer->start_io = 0;
    servicer->num_resources = NUM_RESOURCES_AUDIO_MGR_SERVICER;

    servicer->res_info = &audio_res_info[0];
    // Servicer resource
    servicer->res_info[0].resource = AUDIO_SERVICER_RESID;
    servicer->res_info[0].control_pkt_queue.depth = 0;
    servicer->res_info[0].control_pkt_queue.pkts = NULL;
    servicer->res_info[0].command_map.num_commands = NUM_AUDIO_SERVICER_RESID_CMDS;
    servicer->res_info[0].command_map.commands = audio_servicer_resid_cmd_map;

    // Audio manager resource
    servicer->res_info[1].resource = AUDIO_MGR_RESID;
    servicer->res_info[1].control_pkt_queue.depth = MAX_PKT_QUEUE_LEN_AUDIO_MGR;
    servicer->res_info[1].control_pkt_queue.pkts = &control_pkts_audio_mgr[0];
    servicer->res_info[1].command_map.num_commands = NUM_AUDIO_MGR_RESID_CMDS;
    servicer->res_info[1].command_map.commands = audio_mgr_resid_cmd_map;
    // Initialise payload pointers in the pkt_queue
    init_pkt_queue(&servicer->res_info[1].control_pkt_queue, total_payload_buf_audio_mgr, MAX_PKT_PAYLOAD_AUDIO_MGR);
}

void io_config_servicer_init(servicer_t *servicer)
{
    #include "io_config_cmds_map.h" // Included instead of directly adding code since this file is autogenerated.
    static control_resource_info_t io_config_res_info[NUM_RESOURCES_IO_CONFIG_SERVICER];
    memset(servicer, 0, sizeof(servicer_t));
    // IO Config servicer resource
    servicer->id = IO_CONFIG_SERVICER_RESID;
    servicer->start_io = 0;
    servicer->num_resources = NUM_RESOURCES_IO_CONFIG_SERVICER;

    servicer->res_info = &io_config_res_info[0];
    servicer->res_info[0].resource = IO_CONFIG_SERVICER_RESID;
    servicer->res_info[0].control_pkt_queue.depth = 0;
    servicer->res_info[0].control_pkt_queue.pkts = NULL;
    servicer->res_info[0].command_map.num_commands = NUM_IO_CONFIG_SERVICER_RESID_CMDS;
    servicer->res_info[0].command_map.commands = io_config_servicer_resid_cmd_map;
    servicer->res_info[1].resource = GPO_SERVICER_RESID;
    servicer->res_info[1].control_pkt_queue.depth = 0;
    servicer->res_info[1].control_pkt_queue.pkts = NULL;
    servicer->res_info[1].command_map.num_commands = NUM_GPO_SERVICER_RESID_CMDS;
    servicer->res_info[1].command_map.commands = gpo_servicer_resid_cmd_map;
}

//PP resource
#define MAX_PKT_QUEUE_LEN_PP (4)
#define MAX_PKT_PAYLOAD_PP (20)

// DFU controller resource
#define MAX_PKT_QUEUE_LEN_DFU (2)
#define MAX_PKT_PAYLOAD_DFU (64)
// DFU
void pp_servicer_init(servicer_t *servicer)
{
    #include "pp_cmds_map.h" // Included instead of directly adding code since this file is autogenerated.
    // PP Servicer buffers
    static control_pkt_t control_pkts_pp[MAX_PKT_QUEUE_LEN_PP];
    static uint8_t total_payload_buf_pp[MAX_PKT_QUEUE_LEN_PP * MAX_PKT_PAYLOAD_PP];
    static float NLModel_buffer[NLMODEL_SIZE];
    // Servicer resource info
    static control_resource_info_t pp_res_info[NUM_RESOURCES_PP_SERVICER];

    memset(servicer, 0, sizeof(servicer_t));
    servicer->id = PP_SERVICER_RESID;
    servicer->start_io = 0;
    servicer->num_resources = NUM_RESOURCES_PP_SERVICER;

    servicer->res_info = &pp_res_info[0];
    // Servicer resource
    servicer->res_info[0].resource = PP_SERVICER_RESID;
    servicer->res_info[0].control_pkt_queue.depth = 0;
    servicer->res_info[0].control_pkt_queue.pkts = NULL;
    servicer->res_info[0].command_map.num_commands = NUM_PP_SERVICER_RESID_CMDS;
    servicer->res_info[0].command_map.commands = pp_servicer_resid_cmd_map;
    // PP resource
    servicer->res_info[1].resource = PP_RESID;
    servicer->res_info[1].control_pkt_queue.depth = MAX_PKT_QUEUE_LEN_PP;
    servicer->res_info[1].control_pkt_queue.pkts = &control_pkts_pp[0];
    servicer->res_info[1].command_map.num_commands = NUM_PP_RESID_CMDS;
    servicer->res_info[1].command_map.commands = &pp_resid_cmd_map[0];
    servicer->res_info[1].special_cmd_handler.special_commands_buffer = (uint8_t*)&NLModel_buffer[0];
    servicer->res_info[1].special_cmd_handler.special_cmds_buf_size = NLMODEL_SIZE;
    servicer->res_info[1].special_cmd_handler.special_cmds_buf_overflow_size = 0;

    // Initialise payload pointers in the pkt_queue
    init_pkt_queue(&servicer->res_info[1].control_pkt_queue, total_payload_buf_pp, MAX_PKT_PAYLOAD_PP);
}


void dfu_servicer_init(servicer_t *servicer)
{
    #include "dfu_cmds_map.h" // Included instead of directly adding code since this file is autogenerated.
    // Servicer resource info
    static control_resource_info_t dfu_res_info[NUM_RESOURCES_DFU_SERVICER];

    memset(servicer, 0, sizeof(servicer_t));
    servicer->id = DFU_CONTROLLER_SERVICER_RESID;
    servicer->start_io = 0;
    servicer->num_resources = NUM_RESOURCES_DFU_SERVICER;

    servicer->res_info = &dfu_res_info[0];
    // Servicer resource
    servicer->res_info[0].resource = DFU_CONTROLLER_SERVICER_RESID;
    servicer->res_info[0].control_pkt_queue.depth = 0;
    servicer->res_info[0].control_pkt_queue.pkts = NULL;
    servicer->res_info[0].command_map.num_commands = NUM_DFU_CONTROLLER_SERVICER_RESID_CMDS;
    servicer->res_info[0].command_map.commands = dfu_controller_servicer_resid_cmd_map;

}

void gpo_servicer_init(servicer_t *servicer)
{
    // GPO servicer is a special case that deviates from the generic servicer design.
    // GPO servicer is a servicer but it is also a resource to the IO config servicer.
    // The IO config servicer communicates with the GPO servicer over the internal device_control_gpio_ctx.
    #include "io_config_cmds_map.h" // Included instead of directly adding code since this file is autogenerated.
    static control_resource_info_t gpo_res_info[NUM_RESOURCES_GPO_SERVICER];
    memset(servicer, 0, sizeof(servicer_t));
    // GPO servicer resource
    servicer->id = GPO_SERVICER_RESID;
    servicer->start_io = 1;
    servicer->num_resources = NUM_RESOURCES_GPO_SERVICER;

    servicer->res_info = &gpo_res_info[0];
    servicer->res_info[0].resource = GPO_SERVICER_RESID;
    servicer->res_info[0].control_pkt_queue.depth = 0;
    servicer->res_info[0].control_pkt_queue.pkts = NULL;
    servicer->res_info[0].command_map.num_commands = NUM_GPO_SERVICER_RESID_CMDS;
    servicer->res_info[0].command_map.commands = gpo_servicer_resid_cmd_map;
}

void application_servicer_init(servicer_t *servicer)
{
    #include "application_cmds_map.h" // Included instead of directly adding code since this file is autogenerated.
    static control_resource_info_t application_res_info[NUM_RESOURCES_APPLICATION_SERVICER];
    memset(servicer, 0, sizeof(servicer_t));
    // GPO servicer resource
    servicer->id = APPLICATION_SERVICER_RESID;
    servicer->start_io = 0;
    servicer->num_resources = NUM_RESOURCES_APPLICATION_SERVICER;

    servicer->res_info = &application_res_info[0];
    servicer->res_info[0].resource = APPLICATION_SERVICER_RESID;
    servicer->res_info[0].control_pkt_queue.depth = 0;
    servicer->res_info[0].control_pkt_queue.pkts = NULL;
    servicer->res_info[0].command_map.num_commands = NUM_APPLICATION_SERVICER_RESID_CMDS;
    servicer->res_info[0].command_map.commands = application_servicer_resid_cmd_map;
}

void usb_buffer_servicer_init(servicer_t *servicer)
{
    #include "usb_buffer_cmds_map.h" // Included instead of directly adding code since this file is autogenerated.
    static control_resource_info_t usb_buffer_res_info[NUM_RESOURCES_USB_BUFFER_SERVICER];
    memset(servicer, 0, sizeof(servicer_t));
    // Servicer resource
    servicer->id = USB_BUFFER_SERVICER_RESID;
    servicer->start_io = 0;
    servicer->num_resources = NUM_RESOURCES_USB_BUFFER_SERVICER;

    servicer->res_info = &usb_buffer_res_info[0];
    servicer->res_info[0].resource = USB_BUFFER_SERVICER_RESID;
    servicer->res_info[0].control_pkt_queue.depth = 0;
    servicer->res_info[0].control_pkt_queue.pkts = NULL;
    servicer->res_info[0].command_map.num_commands = NUM_USB_BUFFER_SERVICER_RESID_CMDS;
    servicer->res_info[0].command_map.commands = usb_buffer_servicer_resid_cmd_map;
}

void pll_servicer_init(servicer_t *servicer)
{
    #include "pll_cmds_map.h" // Included instead of directly adding code since this file is autogenerated.
    static control_resource_info_t pll_res_info[NUM_RESOURCES_PLL_SERVICER];
    memset(servicer, 0, sizeof(servicer_t));
    // PLL servicer resource
    servicer->id = PLL_SERVICER_RESID;
    servicer->start_io = 0;
    servicer->num_resources = NUM_RESOURCES_PLL_SERVICER;

    servicer->res_info = &pll_res_info[0];
    servicer->res_info[0].resource = PLL_SERVICER_RESID;
    servicer->res_info[0].control_pkt_queue.depth = 0;
    servicer->res_info[0].control_pkt_queue.pkts = NULL;
    servicer->res_info[0].command_map.num_commands = NUM_PLL_SERVICER_RESID_CMDS;
    servicer->res_info[0].command_map.commands = pll_servicer_resid_cmd_map;
}
