#!/usr/bin/env python
# Copyright 2023 XMOS LIMITED.
# This Software is subject to the terms of the XCORE VocalFusion Licence.

import pathlib
import yaml_autogen
import yaml_autogen.outputs.documentation as documentation


REPO_ROOT = (pathlib.Path(__file__).parent / "../..").resolve()
AUTOGENERATED_DOCUMENTATION_SOURCES = {
    "aec_cmds.csv": ["aec_cmds.yaml", "shf_aec_cmds.yaml"],
    "application_cmds.csv": ["application_cmds.yaml"],
    "audio_cmds.csv": ["audio_cmds.yaml"],
    "io_config_cmds.csv": ["io_config_cmds.yaml"],
    "pll_cmds.csv": ["pll_cmds.yaml"],
    "pp_cmds.csv": ["pp_cmds.yaml", "shf_pp_cmds.yaml"],
    "usb_buffer_cmds.csv": ["usb_buffer_cmds.yaml"],
}


def render_docs():
    doc_template = (
        yaml_autogen.get_templates() / "documentation" / "doc_cmd_list.csv.jinja"
    ).resolve()
    defaults = (
        REPO_ROOT
        / "app_xvf3800"
        / "autogeneration"
        / "yaml_files"
        / "settings_and_defaults"
        / "product/control_param_values.yaml"
    ).resolve()
    for document, sources in AUTOGENERATED_DOCUMENTATION_SOURCES.items():
        doc_path = (REPO_ROOT / "doc" / "autogenerated" / document).resolve()
        for idx, source in enumerate(sources):
            sources[idx] = (
                REPO_ROOT
                / "app_xvf3800"
                / "autogeneration"
                / "yaml_files"
                / "control_commands"
                / source
            ).resolve()

        render_data = documentation.generate_render_data(sources, True, True, defaults)
        documentation.render(render_data, doc_template, doc_path)


if __name__ == "__main__":
    render_docs()
